"""Application ToolSweep case table for Runtime Matrix strict coverage."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from lean_constellation.tools import build_application_tool_specs


ToolCaseStatus = Literal["implemented", "pending_env", "pending_fixture"]
RestorePolicy = Literal["none", "checkpoint", "isolated_workspace"]


@dataclass(frozen=True)
class ToolCase:
    tool_name: str
    status: ToolCaseStatus
    category: str
    reason: str
    view_key: str | None = None
    agent_type: str | None = None
    covered_view_keys: tuple[str, ...] = ()
    covered_agent_types: tuple[str, ...] = ()
    restore_policy: RestorePolicy = "none"
    expected_failure: bool = False

    @property
    def implemented(self) -> bool:
        return self.status == "implemented"


IMPLEMENTED_TOOL_CASES: dict[str, ToolCase] = {
    "get_preparation_input": ToolCase(
        tool_name="get_preparation_input",
        status="implemented",
        category="repo_preparation_read",
        reason="Read-only preparation input call covered by strict ToolSweep runner.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "list_preparation_requirements": ToolCase(
        tool_name="list_preparation_requirements",
        status="implemented",
        category="repo_preparation_read",
        reason="Current-preparation-scoped requirement list covered by strict ToolSweep runner.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "get_preparation_requirement": ToolCase(
        tool_name="get_preparation_requirement",
        status="implemented",
        category="repo_preparation_read",
        reason="Current-preparation-scoped requirement detail covered by strict ToolSweep runner.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "search_github_lean_repositories": ToolCase(
        tool_name="search_github_lean_repositories",
        status="pending_env",
        category="github_remote_read",
        reason="Covered by strict live-env ToolSweep when LEAN_CONSTELLATION_STRICT_LIVE_TOOL_SWEEP=1.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "inspect_github_lean_repository": ToolCase(
        tool_name="inspect_github_lean_repository",
        status="pending_env",
        category="github_remote_read",
        reason="Covered by strict live-env ToolSweep when LEAN_CONSTELLATION_STRICT_LIVE_TOOL_SWEEP=1.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "probe_github_lean_repo_candidate": ToolCase(
        tool_name="probe_github_lean_repo_candidate",
        status="pending_env",
        category="github_remote_read",
        reason="Covered by strict live-env ToolSweep when LEAN_CONSTELLATION_STRICT_LIVE_TOOL_SWEEP=1.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "get_github_repository": ToolCase(
        tool_name="get_github_repository",
        status="pending_env",
        category="github_remote_read",
        reason="Covered by strict live-env ToolSweep when LEAN_CONSTELLATION_STRICT_LIVE_TOOL_SWEEP=1.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "list_github_repository_tree": ToolCase(
        tool_name="list_github_repository_tree",
        status="pending_env",
        category="github_remote_read",
        reason="Covered by strict live-env ToolSweep when LEAN_CONSTELLATION_STRICT_LIVE_TOOL_SWEEP=1.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "read_github_repository_file": ToolCase(
        tool_name="read_github_repository_file",
        status="pending_env",
        category="github_remote_read",
        reason="Covered by strict live-env ToolSweep when LEAN_CONSTELLATION_STRICT_LIVE_TOOL_SWEEP=1.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "search_github_code": ToolCase(
        tool_name="search_github_code",
        status="pending_env",
        category="github_remote_read",
        reason="Covered by strict live-env ToolSweep when LEAN_CONSTELLATION_STRICT_LIVE_TOOL_SWEEP=1.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "normalize_resource_target": ToolCase(
        tool_name="normalize_resource_target",
        status="implemented",
        category="resource_context_read",
        reason="Read-only resource target normalization call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "acquire_resource_material": ToolCase(
        tool_name="acquire_resource_material",
        status="implemented",
        category="resource_acquisition_write",
        reason="Checkpointed local resource acquisition covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
        restore_policy="checkpoint",
    ),
    "extract_resource_artifact": ToolCase(
        tool_name="extract_resource_artifact",
        status="implemented",
        category="resource_acquisition_write",
        reason="Checkpointed local resource artifact text extraction covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
        restore_policy="checkpoint",
    ),
    "import_resource_material": ToolCase(
        tool_name="import_resource_material",
        status="implemented",
        category="resource_acquisition_write",
        reason="Checkpointed local resource material import covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
        restore_policy="checkpoint",
    ),
    "normalize_resource_text_material": ToolCase(
        tool_name="normalize_resource_text_material",
        status="implemented",
        category="resource_acquisition_write",
        reason="Checkpointed local resource text normalization covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
        restore_policy="checkpoint",
    ),
    "search_mathlib_index": ToolCase(
        tool_name="search_mathlib_index",
        status="implemented",
        category="mathlib_index_read",
        reason="Local Mathlib index search call covered by strict ToolSweep runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
    ),
    "get_current_node_contract": ToolCase(
        tool_name="get_current_node_contract",
        status="implemented",
        category="node_contract_read",
        reason="Current node contract read call covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "list_current_node_deps": ToolCase(
        tool_name="list_current_node_deps",
        status="implemented",
        category="node_contract_read",
        reason="Current node dependency read call covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "get_material_context": ToolCase(
        tool_name="get_material_context",
        status="implemented",
        category="resource_context_read",
        reason="Read-only material context call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "find_duplicate_resource": ToolCase(
        tool_name="find_duplicate_resource",
        status="implemented",
        category="resource_context_read",
        reason="Read-only duplicate resource lookup covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "list_resources": ToolCase(
        tool_name="list_resources",
        status="implemented",
        category="resource_library_read",
        reason="Read-only resource library list call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "get_resource": ToolCase(
        tool_name="get_resource",
        status="implemented",
        category="resource_library_read",
        reason="Read-only resource lookup call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "read_resource_range": ToolCase(
        tool_name="read_resource_range",
        status="implemented",
        category="resource_library_read",
        reason="Read-only normalized resource range call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "search_resource_text": ToolCase(
        tool_name="search_resource_text",
        status="implemented",
        category="resource_library_read",
        reason="Read-only resource text search call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "get_resource_draft": ToolCase(
        tool_name="get_resource_draft",
        status="implemented",
        category="resource_draft_read",
        reason="Read-only resource draft lookup call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "check_resource_draft": ToolCase(
        tool_name="check_resource_draft",
        status="implemented",
        category="resource_draft_read",
        reason="Read-only resource draft validation call covered by strict ToolSweep runner.",
        view_key="resource_curator",
        agent_type="ResourceCuratorAgent",
    ),
    "scan_source_corpus": ToolCase(
        tool_name="scan_source_corpus",
        status="implemented",
        category="source_corpus_read",
        reason="Read-only source corpus scan call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "check_source_corpus_draft": ToolCase(
        tool_name="check_source_corpus_draft",
        status="implemented",
        category="source_corpus_read",
        reason="Read-only source corpus draft gate call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "get_source_index": ToolCase(
        tool_name="get_source_index",
        status="implemented",
        category="source_index_read",
        reason="Read-only source index lookup covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "set_source_index_overview": ToolCase(
        tool_name="set_source_index_overview",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source index overview update covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "create_source_block": ToolCase(
        tool_name="create_source_block",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source block creation covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "update_source_block": ToolCase(
        tool_name="update_source_block",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source block update covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "add_source_block_ref": ToolCase(
        tool_name="add_source_block_ref",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source block ref creation covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "remove_source_block_ref": ToolCase(
        tool_name="remove_source_block_ref",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source block ref removal covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "create_source_link": ToolCase(
        tool_name="create_source_link",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source link creation covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "mark_block_refs_done": ToolCase(
        tool_name="mark_block_refs_done",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source block refs gate covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "mark_block_links_done": ToolCase(
        tool_name="mark_block_links_done",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source block links gate covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "mark_block_completed": ToolCase(
        tool_name="mark_block_completed",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source block completion gate covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "set_file_survey_status": ToolCase(
        tool_name="set_file_survey_status",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source file survey status update covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "set_file_indexing_status": ToolCase(
        tool_name="set_file_indexing_status",
        status="implemented",
        category="source_index_write",
        reason="Checkpointed source file indexing status update covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
        restore_policy="checkpoint",
    ),
    "validate_source_index": ToolCase(
        tool_name="validate_source_index",
        status="implemented",
        category="source_index_read",
        reason="Read-only source index validation call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "get_source_index_coverage": ToolCase(
        tool_name="get_source_index_coverage",
        status="implemented",
        category="source_index_read",
        reason="Read-only source index coverage call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "search_source_text": ToolCase(
        tool_name="search_source_text",
        status="implemented",
        category="source_material_read",
        reason="Read-only source material search call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "read_source_range": ToolCase(
        tool_name="read_source_range",
        status="implemented",
        category="source_material_read",
        reason="Read-only source range call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "validate_source_range": ToolCase(
        tool_name="validate_source_range",
        status="implemented",
        category="source_material_read",
        reason="Read-only source range validation call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "preview_source_ref": ToolCase(
        tool_name="preview_source_ref",
        status="implemented",
        category="source_material_read",
        reason="Read-only source ref preview call covered by strict ToolSweep runner.",
        view_key="source_index_builder",
        agent_type="SourceIndexBuilderAgent",
    ),
    "acquire_source_material": ToolCase(
        tool_name="acquire_source_material",
        status="implemented",
        category="source_acquisition_write",
        reason="Checkpointed local source material acquisition covered by strict ToolSweep runner.",
        view_key="source_corpus_prepare",
        agent_type="SourceCorpusPrepareAgent",
        restore_policy="checkpoint",
    ),
    "extract_source_artifact": ToolCase(
        tool_name="extract_source_artifact",
        status="implemented",
        category="source_acquisition_write",
        reason="Checkpointed local source artifact text extraction covered by strict ToolSweep runner.",
        view_key="source_corpus_prepare",
        agent_type="SourceCorpusPrepareAgent",
        restore_policy="checkpoint",
    ),
    "import_source_material": ToolCase(
        tool_name="import_source_material",
        status="implemented",
        category="source_acquisition_write",
        reason="Checkpointed local source material import covered by strict ToolSweep runner.",
        view_key="source_corpus_prepare",
        agent_type="SourceCorpusPrepareAgent",
        restore_policy="checkpoint",
    ),
    "normalize_source_text_material": ToolCase(
        tool_name="normalize_source_text_material",
        status="implemented",
        category="source_acquisition_write",
        reason="Checkpointed local source text normalization covered by strict ToolSweep runner.",
        view_key="source_corpus_prepare",
        agent_type="SourceCorpusPrepareAgent",
        restore_policy="checkpoint",
    ),
    "get_preparation_start_preflight": ToolCase(
        tool_name="get_preparation_start_preflight",
        status="implemented",
        category="repo_preparation_read",
        reason="Read-only preparation start preflight covered by strict ToolSweep runner.",
        view_key="repo_format_discovery",
        agent_type="RepoFormatDiscoveryAgent",
    ),
    "check_root_main_handoff_interfaces": ToolCase(
        tool_name="check_root_main_handoff_interfaces",
        status="implemented",
        category="root_interface_prepare_read",
        reason="Read-only root handoff interface gate covered by strict ToolSweep runner.",
        view_key="root_interface_prepare",
        agent_type="RootInterfacePrepareAgent",
    ),
    "list_root_interfaces": ToolCase(
        tool_name="list_root_interfaces",
        status="implemented",
        category="root_interface_prepare_read",
        reason="Read-only root Main interface listing covered by strict ToolSweep runner.",
        view_key="root_interface_prepare",
        agent_type="RootInterfacePrepareAgent",
    ),
    "add_root_interface": ToolCase(
        tool_name="add_root_interface",
        status="implemented",
        category="root_interface_prepare_write",
        reason="Checkpointed root Main supplement interface add covered by strict ToolSweep runner.",
        view_key="root_interface_prepare",
        agent_type="RootInterfacePrepareAgent",
        restore_policy="checkpoint",
    ),
    "inspect_workspace_for_coordinator": ToolCase(
        tool_name="inspect_workspace_for_coordinator",
        status="implemented",
        category="workspace_catalog_read",
        reason="Read-only workspace coordinator inspection covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "list_ready_provider_repos": ToolCase(
        tool_name="list_ready_provider_repos",
        status="implemented",
        category="workspace_catalog_read",
        reason="Read-only ready provider list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "list_open_requirement_groups": ToolCase(
        tool_name="list_open_requirement_groups",
        status="implemented",
        category="workspace_requirement_read",
        reason="Read-only open requirement group list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "get_requirement_group": ToolCase(
        tool_name="get_requirement_group",
        status="implemented",
        category="workspace_requirement_read",
        reason="Read-only requirement group lookup covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "list_current_lake_dependencies": ToolCase(
        tool_name="list_current_lake_dependencies",
        status="implemented",
        category="lake_dependency_read",
        reason="Read-only Lake dependency list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "get_node_contract": ToolCase(
        tool_name="get_node_contract",
        status="implemented",
        category="node_contract_read",
        reason="Read-only node contract lookup covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "get_node_tree": ToolCase(
        tool_name="get_node_tree",
        status="implemented",
        category="node_tree_read",
        reason="Read-only node tree lookup covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "get_node": ToolCase(
        tool_name="get_node",
        status="implemented",
        category="node_tree_read",
        reason="Read-only node metadata lookup covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "list_runnable_content_nodes": ToolCase(
        tool_name="list_runnable_content_nodes",
        status="implemented",
        category="content_task_admission_read",
        reason="Read-only runnable content node list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "create_scope_node": ToolCase(
        tool_name="create_scope_node",
        status="implemented",
        category="node_tree_write",
        reason="Checkpointed scope node creation covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "create_content_node": ToolCase(
        tool_name="create_content_node",
        status="implemented",
        category="node_tree_write",
        reason="Checkpointed content node creation covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "update_node_contract_text": ToolCase(
        tool_name="update_node_contract_text",
        status="implemented",
        category="node_contract_write",
        reason="Checkpointed node contract text update covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "preview_delete_node": ToolCase(
        tool_name="preview_delete_node",
        status="implemented",
        category="node_tree_read",
        reason="Read-only node delete preview covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "delete_node": ToolCase(
        tool_name="delete_node",
        status="implemented",
        category="node_tree_write",
        reason="Checkpointed node soft-delete covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "list_visible_nodes": ToolCase(
        tool_name="list_visible_nodes",
        status="implemented",
        category="node_visibility_read_current",
        reason="Read-only visible node list covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "add_current_node_dep": ToolCase(
        tool_name="add_current_node_dep",
        status="implemented",
        category="node_contract_dependency_write",
        reason="Checkpointed current node dependency addition covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "remove_current_node_dep": ToolCase(
        tool_name="remove_current_node_dep",
        status="implemented",
        category="node_contract_dependency_write",
        reason="Checkpointed current node dependency removal covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "add_current_material_ref": ToolCase(
        tool_name="add_current_material_ref",
        status="implemented",
        category="node_contract_material_write",
        reason="Checkpointed current node material ref addition covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "remove_current_material_ref": ToolCase(
        tool_name="remove_current_material_ref",
        status="implemented",
        category="node_contract_material_write",
        reason="Checkpointed current node material ref removal covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "list_current_node_material_refs": ToolCase(
        tool_name="list_current_node_material_refs",
        status="implemented",
        category="node_contract_read",
        reason="Read-only current-node material ref list covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "list_node_material_refs": ToolCase(
        tool_name="list_node_material_refs",
        status="implemented",
        category="node_contract_read",
        reason="Read-only coordinator node material ref list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "list_node_interfaces": ToolCase(
        tool_name="list_node_interfaces",
        status="implemented",
        category="scope_export_interface_read",
        reason="Read-only node interface list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "add_node_interface": ToolCase(
        tool_name="add_node_interface",
        status="implemented",
        category="scope_export_interface_write",
        reason="Checkpointed node interface addition covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "update_node_interface": ToolCase(
        tool_name="update_node_interface",
        status="implemented",
        category="scope_export_interface_write",
        reason="Checkpointed node interface update covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "remove_node_interface": ToolCase(
        tool_name="remove_node_interface",
        status="implemented",
        category="scope_export_interface_write",
        reason="Checkpointed node interface removal covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "list_scope_export_candidates": ToolCase(
        tool_name="list_scope_export_candidates",
        status="implemented",
        category="scope_export_interface_read",
        reason="Read-only scope export candidate list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "list_scope_exports": ToolCase(
        tool_name="list_scope_exports",
        status="implemented",
        category="scope_export_interface_read",
        reason="Read-only scope export list covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "add_scope_export": ToolCase(
        tool_name="add_scope_export",
        status="implemented",
        category="scope_export_interface_write",
        reason="Checkpointed scope export addition covered by strict scope export ToolSweep.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "remove_scope_export": ToolCase(
        tool_name="remove_scope_export",
        status="implemented",
        category="scope_export_interface_write",
        reason="Checkpointed scope export removal covered by strict scope export ToolSweep.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "bind_node_interface": ToolCase(
        tool_name="bind_node_interface",
        status="implemented",
        category="scope_export_interface_write",
        reason="Checkpointed scope interface binding covered by strict scope export ToolSweep.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "unbind_node_interface": ToolCase(
        tool_name="unbind_node_interface",
        status="implemented",
        category="scope_export_interface_write",
        reason="Checkpointed scope interface unbinding covered by strict scope export ToolSweep.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
        restore_policy="checkpoint",
    ),
    "get_scope_close_view": ToolCase(
        tool_name="get_scope_close_view",
        status="implemented",
        category="scope_close_read",
        reason="Read-only scope close view covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "get_repo_ready_node_view": ToolCase(
        tool_name="get_repo_ready_node_view",
        status="implemented",
        category="repo_ready_read",
        reason="Read-only repo ready node view covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "check_content_task_admission": ToolCase(
        tool_name="check_content_task_admission",
        status="implemented",
        category="content_task_admission_read",
        reason="Read-only content task admission gate covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "check_content_node_batch": ToolCase(
        tool_name="check_content_node_batch",
        status="implemented",
        category="content_task_admission_read",
        reason="Read-only content node batch gate covered by strict ToolSweep runner.",
        view_key="native_repo_coordinator",
        agent_type="CoordinatorAgent",
    ),
    "get_mathlib_module_entry": ToolCase(
        tool_name="get_mathlib_module_entry",
        status="implemented",
        category="mathlib_index_read",
        reason="Read-only local Mathlib module entry lookup covered by strict ToolSweep runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
    ),
    "get_mathlib_decl_entry": ToolCase(
        tool_name="get_mathlib_decl_entry",
        status="implemented",
        category="mathlib_index_read",
        reason="Read-only local Mathlib declaration entry lookup covered by strict ToolSweep runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
    ),
    "record_mathlib_module": ToolCase(
        tool_name="record_mathlib_module",
        status="implemented",
        category="mathlib_index_write",
        reason="Checkpointed checked Mathlib module index write covered by strict ToolSweep runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
        restore_policy="checkpoint",
    ),
    "record_mathlib_decl": ToolCase(
        tool_name="record_mathlib_decl",
        status="implemented",
        category="mathlib_index_write",
        reason="Checkpointed checked Mathlib declaration index write covered by strict ToolSweep runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
        restore_policy="checkpoint",
    ),
    "add_mathlib_module_important_decl": ToolCase(
        tool_name="add_mathlib_module_important_decl",
        status="implemented",
        category="mathlib_index_write",
        reason="Checkpointed Mathlib module important declaration write covered by strict ToolSweep runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
        restore_policy="checkpoint",
    ),
    "ingest_mathlib_candidate": ToolCase(
        tool_name="ingest_mathlib_candidate",
        status="implemented",
        category="mathlib_index_write",
        reason="Checkpointed cached Mathlib candidate ingestion covered by strict ToolSweep runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
        restore_policy="checkpoint",
    ),
    "get_current_node_mathlib_hints": ToolCase(
        tool_name="get_current_node_mathlib_hints",
        status="implemented",
        category="node_mathlib_hint_read",
        reason="Read-only current node Mathlib hint view covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "add_current_mathlib_hints": ToolCase(
        tool_name="add_current_mathlib_hints",
        status="implemented",
        category="node_mathlib_hint_write",
        reason="Checkpointed atomic current-node Mathlib hint addition covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "remove_current_mathlib_module_hint": ToolCase(
        tool_name="remove_current_mathlib_module_hint",
        status="implemented",
        category="node_mathlib_hint_write",
        reason="Checkpointed current node Mathlib module hint removal covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "remove_current_mathlib_decl_hint": ToolCase(
        tool_name="remove_current_mathlib_decl_hint",
        status="implemented",
        category="node_mathlib_hint_write",
        reason="Checkpointed current node Mathlib declaration hint removal covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "validate_current_node_mathlib_hints": ToolCase(
        tool_name="validate_current_node_mathlib_hints",
        status="implemented",
        category="node_mathlib_hint_read",
        reason="Read-only current node Mathlib hint validation covered by strict ToolSweep runner.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "check_mathlib_name": ToolCase(
        tool_name="check_mathlib_name",
        status="implemented",
        category="mathlib_navigation",
        reason="Real Lake-backed Mathlib name check covered by strict ToolSweep local boundary runner.",
        view_key="mathlib_recon",
        agent_type="MathlibReconAgent",
    ),
    "inspect_adapter_input": ToolCase(
        tool_name="inspect_adapter_input",
        status="implemented",
        category="adapter_input_read",
        reason="Read-only adapter preparation input inspection covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "get_adapter_upstream_metadata": ToolCase(
        tool_name="get_adapter_upstream_metadata",
        status="implemented",
        category="upstream_metadata_read",
        reason="Read-only adapter upstream metadata lookup covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "get_adapter_upstream_status": ToolCase(
        tool_name="get_adapter_upstream_status",
        status="implemented",
        category="upstream_metadata_read",
        reason="Read-only adapter upstream status lookup covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "search_upstream_declarations": ToolCase(
        tool_name="search_upstream_declarations",
        status="implemented",
        category="upstream_navigation",
        reason="Local upstream repo declaration search covered through ToolFacade/MCP with LeanToolchain fallback.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "search_upstream_modules": ToolCase(
        tool_name="search_upstream_modules",
        status="implemented",
        category="upstream_navigation",
        reason="Local upstream repo module search covered through ToolFacade/MCP with LeanToolchain fallback.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "list_upstream_module_declarations": ToolCase(
        tool_name="list_upstream_module_declarations",
        status="implemented",
        category="upstream_navigation",
        reason="Local upstream module declaration listing covered through ToolFacade/MCP with LeanToolchain fallback.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "inspect_upstream_declaration": ToolCase(
        tool_name="inspect_upstream_declaration",
        status="implemented",
        category="upstream_navigation",
        reason="Local upstream declaration inspection covered through ToolFacade/MCP with LeanToolchain fallback.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "read_upstream_source_context": ToolCase(
        tool_name="read_upstream_source_context",
        status="implemented",
        category="upstream_navigation",
        reason="Local upstream source context read covered through ToolFacade/MCP with LeanToolchain fallback.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "capture_upstream_declaration_code": ToolCase(
        tool_name="capture_upstream_declaration_code",
        status="implemented",
        category="upstream_navigation",
        reason="Local upstream declaration capture covered through ToolFacade/MCP with LeanToolchain fallback.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "inspect_upstream_module_imports": ToolCase(
        tool_name="inspect_upstream_module_imports",
        status="implemented",
        category="upstream_navigation",
        reason="Local upstream module import inspection covered through ToolFacade/MCP with LeanToolchain fallback.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "create_adapter_decl": ToolCase(
        tool_name="create_adapter_decl",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter declaration creation covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "set_adapter_statement_formal": ToolCase(
        tool_name="set_adapter_statement_formal",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter formal statement write covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "set_adapter_statement_nl": ToolCase(
        tool_name="set_adapter_statement_nl",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter statement natural-language write covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "add_adapter_statement_origin": ToolCase(
        tool_name="add_adapter_statement_origin",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter statement origin write covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "add_adapter_statement_dep": ToolCase(
        tool_name="add_adapter_statement_dep",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter statement dependency addition covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "remove_adapter_statement_dep": ToolCase(
        tool_name="remove_adapter_statement_dep",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter statement dependency removal covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "set_adapter_proof_formal": ToolCase(
        tool_name="set_adapter_proof_formal",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter formal proof write covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "set_adapter_proof_nl": ToolCase(
        tool_name="set_adapter_proof_nl",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter proof natural-language write covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "add_adapter_proof_origin": ToolCase(
        tool_name="add_adapter_proof_origin",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter proof origin write covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "add_adapter_proof_dep": ToolCase(
        tool_name="add_adapter_proof_dep",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter proof dependency addition covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "remove_adapter_proof_dep": ToolCase(
        tool_name="remove_adapter_proof_dep",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter proof dependency removal covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "list_adapter_decls": ToolCase(
        tool_name="list_adapter_decls",
        status="implemented",
        category="adapter_decl_catalog_read",
        reason="Read-only adapter declaration list covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "inspect_adapter_decl": ToolCase(
        tool_name="inspect_adapter_decl",
        status="implemented",
        category="adapter_decl_catalog_read",
        reason="Read-only adapter declaration inspection covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "list_registered_adapter_modules": ToolCase(
        tool_name="list_registered_adapter_modules",
        status="implemented",
        category="adapter_decl_catalog_read",
        reason="Read-only registered adapter module list covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "check_adapter_decl_completeness": ToolCase(
        tool_name="check_adapter_decl_completeness",
        status="implemented",
        category="adapter_decl_catalog_read",
        reason="Read-only adapter declaration completeness gate covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "find_adapter_decl_by_upstream": ToolCase(
        tool_name="find_adapter_decl_by_upstream",
        status="implemented",
        category="adapter_decl_catalog_read",
        reason="Read-only duplicate upstream declaration lookup covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "finalize_adapter_decl": ToolCase(
        tool_name="finalize_adapter_decl",
        status="implemented",
        category="adapter_decl_catalog_write",
        reason="Checkpointed adapter declaration finalization covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "bind_adapter_interface": ToolCase(
        tool_name="bind_adapter_interface",
        status="implemented",
        category="adapter_interface_binding_write",
        reason="Checkpointed adapter interface binding covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "unbind_adapter_interface": ToolCase(
        tool_name="unbind_adapter_interface",
        status="implemented",
        category="adapter_interface_binding_write",
        reason="Checkpointed adapter interface unbinding covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
        restore_policy="checkpoint",
    ),
    "list_unbound_adapter_interfaces": ToolCase(
        tool_name="list_unbound_adapter_interfaces",
        status="implemented",
        category="adapter_interface_binding_read",
        reason="Read-only unbound adapter interface list covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "validate_adapter_interface_bindings": ToolCase(
        tool_name="validate_adapter_interface_bindings",
        status="implemented",
        category="adapter_interface_binding_read",
        reason="Read-only adapter interface binding validation covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "preview_adapter_import_modules": ToolCase(
        tool_name="preview_adapter_import_modules",
        status="implemented",
        category="adapter_projection_check",
        reason="Read-only adapter import preview covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "check_adapter_projection": ToolCase(
        tool_name="check_adapter_projection",
        status="implemented",
        category="adapter_projection_check",
        reason="Read-only adapter projection consistency gate covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "check_adapter_ready": ToolCase(
        tool_name="check_adapter_ready",
        status="implemented",
        category="adapter_ready_read",
        reason="Read-only adapter ready gate covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "check_adapter_catalog_ready_preflight": ToolCase(
        tool_name="check_adapter_catalog_ready_preflight",
        status="implemented",
        category="adapter_ready_read",
        reason="Read-only adapter catalog ready preflight covered by strict ToolSweep runner.",
        view_key="adapter_repo_import",
        agent_type="AdapterDeclCatalogAgent",
    ),
    "set_statement_nl": ToolCase(
        tool_name="set_statement_nl",
        status="implemented",
        category="decl_stage_statement_nl_write",
        reason="Checkpointed statement NL text write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_worker",
        agent_type="StatementNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "read_statement_nl": ToolCase(
        tool_name="read_statement_nl",
        status="implemented",
        category="decl_stage_statement_nl_read",
        reason="Complete nested Statement NL truth read covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_worker",
        agent_type="StatementNLWorkerAgent",
    ),
    "add_statement_source_origin": ToolCase(
        tool_name="add_statement_source_origin",
        status="implemented",
        category="decl_stage_statement_nl_write",
        reason="Typed statement source-origin write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_worker",
        agent_type="StatementNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "add_statement_resource_origin": ToolCase(
        tool_name="add_statement_resource_origin",
        status="implemented",
        category="decl_stage_statement_nl_write",
        reason="Typed statement resource-origin write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_worker",
        agent_type="StatementNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "remove_statement_origin": ToolCase(
        tool_name="remove_statement_origin",
        status="implemented",
        category="decl_stage_statement_nl_write",
        reason="Typed statement origin removal covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_worker",
        agent_type="StatementNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "clear_statement_origins": ToolCase(
        tool_name="clear_statement_origins",
        status="implemented",
        category="decl_stage_statement_nl_write",
        reason="Typed statement origin clearing covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_worker",
        agent_type="StatementNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "list_statement_dependencies": ToolCase(
        tool_name="list_statement_dependencies",
        status="implemented",
        category="decl_stage_statement_dep_read",
        reason="Compact typed statement dependency list covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
    ),
    "add_statement_repo_dependency": ToolCase(
        tool_name="add_statement_repo_dependency",
        status="implemented",
        category="decl_stage_statement_formal_dep_write",
        reason="Singular typed project statement dependency write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "add_statement_repo_dependencies": ToolCase(
        tool_name="add_statement_repo_dependencies",
        status="implemented",
        category="decl_stage_statement_formal_dep_write",
        reason="Batch typed project statement dependency write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "add_statement_mathlib_dependency": ToolCase(
        tool_name="add_statement_mathlib_dependency",
        status="implemented",
        category="decl_stage_statement_formal_dep_write",
        reason="Singular verified Mathlib statement dependency transaction covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "add_statement_mathlib_dependencies": ToolCase(
        tool_name="add_statement_mathlib_dependencies",
        status="implemented",
        category="decl_stage_statement_formal_dep_write",
        reason="Batch verified Mathlib statement dependency transaction covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "remove_statement_dep": ToolCase(
        tool_name="remove_statement_dep",
        status="implemented",
        category="decl_stage_statement_formal_dep_write",
        reason="Typed statement dependency removal covered through Statement Formal worker in strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "clear_statement_deps": ToolCase(
        tool_name="clear_statement_deps",
        status="implemented",
        category="decl_stage_statement_formal_dep_write",
        reason="Typed statement dependency clearing covered through Statement Formal worker in strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "prepare_statement_formal_file": ToolCase(
        tool_name="prepare_statement_formal_file",
        status="implemented",
        category="decl_stage_statement_formal_file",
        reason="Statement formal file preparation covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "capture_statement_formal_file": ToolCase(
        tool_name="capture_statement_formal_file",
        status="implemented",
        category="decl_stage_statement_formal_file",
        reason="Statement formal file capture covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "set_proof_nl": ToolCase(
        tool_name="set_proof_nl",
        status="implemented",
        category="decl_stage_proof_nl_write",
        reason="Typed proof NL text write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "read_proof_nl": ToolCase(
        tool_name="read_proof_nl",
        status="implemented",
        category="decl_stage_proof_nl_read",
        reason="Complete nested Proof NL truth read covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
    ),
    "read_formal": ToolCase(
        tool_name="read_formal",
        status="implemented",
        category="decl_stage_formal_read",
        reason="Stage-aware formal Lean source read with managed docstrings omitted by default covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
        covered_view_keys=("statement_formal_worker", "proof_formal_worker"),
        covered_agent_types=("StatementFormalWorkerAgent", "ProofFormalWorkerAgent"),
    ),
    "add_proof_source_origin": ToolCase(
        tool_name="add_proof_source_origin",
        status="implemented",
        category="decl_stage_proof_nl_write",
        reason="Typed proof source-origin write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "add_proof_resource_origin": ToolCase(
        tool_name="add_proof_resource_origin",
        status="implemented",
        category="decl_stage_proof_nl_write",
        reason="Typed proof resource-origin write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "remove_proof_origin": ToolCase(
        tool_name="remove_proof_origin",
        status="implemented",
        category="decl_stage_proof_nl_write",
        reason="Typed proof origin removal covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "clear_proof_origins": ToolCase(
        tool_name="clear_proof_origins",
        status="implemented",
        category="decl_stage_proof_nl_write",
        reason="Typed proof origin clearing covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        restore_policy="checkpoint",
    ),
    "list_proof_dependencies": ToolCase(
        tool_name="list_proof_dependencies",
        status="implemented",
        category="decl_stage_proof_dep_read",
        reason="Compact typed proof dependency list covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        covered_view_keys=("proof_nl_worker", "proof_formal_worker"),
        covered_agent_types=("ProofNLWorkerAgent", "ProofFormalWorkerAgent"),
    ),
    "add_proof_repo_dependency": ToolCase(
        tool_name="add_proof_repo_dependency",
        status="implemented",
        category="decl_stage_proof_dep_write",
        reason="Singular typed project proof dependency write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        covered_view_keys=("proof_nl_worker", "proof_formal_worker"),
        covered_agent_types=("ProofNLWorkerAgent", "ProofFormalWorkerAgent"),
        restore_policy="checkpoint",
    ),
    "add_proof_repo_dependencies": ToolCase(
        tool_name="add_proof_repo_dependencies",
        status="implemented",
        category="decl_stage_proof_dep_write",
        reason="Batch typed project proof dependency write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        covered_view_keys=("proof_nl_worker", "proof_formal_worker"),
        covered_agent_types=("ProofNLWorkerAgent", "ProofFormalWorkerAgent"),
        restore_policy="checkpoint",
    ),
    "add_proof_mathlib_dependency": ToolCase(
        tool_name="add_proof_mathlib_dependency",
        status="implemented",
        category="decl_stage_proof_dep_write",
        reason="Singular verified Mathlib proof dependency transaction covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        covered_view_keys=("proof_nl_worker", "proof_formal_worker"),
        covered_agent_types=("ProofNLWorkerAgent", "ProofFormalWorkerAgent"),
        restore_policy="checkpoint",
    ),
    "add_proof_mathlib_dependencies": ToolCase(
        tool_name="add_proof_mathlib_dependencies",
        status="implemented",
        category="decl_stage_proof_dep_write",
        reason="Batch verified Mathlib proof dependency transaction covered for Proof NL and Proof Formal worker surfaces by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        covered_view_keys=("proof_nl_worker", "proof_formal_worker"),
        covered_agent_types=("ProofNLWorkerAgent", "ProofFormalWorkerAgent"),
        restore_policy="checkpoint",
    ),
    "remove_proof_dep": ToolCase(
        tool_name="remove_proof_dep",
        status="implemented",
        category="decl_stage_proof_dep_write",
        reason="Typed proof dependency removal covered for Proof NL and Proof Formal worker surfaces by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        covered_view_keys=("proof_nl_worker", "proof_formal_worker"),
        covered_agent_types=("ProofNLWorkerAgent", "ProofFormalWorkerAgent"),
        restore_policy="checkpoint",
    ),
    "clear_proof_deps": ToolCase(
        tool_name="clear_proof_deps",
        status="implemented",
        category="decl_stage_proof_dep_write",
        reason="Typed proof dependency clearing covered for Proof NL and Proof Formal worker surfaces by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_worker",
        agent_type="ProofNLWorkerAgent",
        covered_view_keys=("proof_nl_worker", "proof_formal_worker"),
        covered_agent_types=("ProofNLWorkerAgent", "ProofFormalWorkerAgent"),
        restore_policy="checkpoint",
    ),
    "prepare_proof_formal_file": ToolCase(
        tool_name="prepare_proof_formal_file",
        status="implemented",
        category="decl_stage_proof_formal_file",
        reason="Proof formal file preparation covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_formal_worker",
        agent_type="ProofFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "capture_proof_formal_file": ToolCase(
        tool_name="capture_proof_formal_file",
        status="implemented",
        category="decl_stage_proof_formal_file",
        reason="Proof formal file capture covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_formal_worker",
        agent_type="ProofFormalWorkerAgent",
        restore_policy="checkpoint",
    ),
    "check_decl_file_snapshot_sync": ToolCase(
        tool_name="check_decl_file_snapshot_sync",
        status="implemented",
        category="decl_stage_formal_file_read",
        reason="Statement and proof capture sync gates covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
    ),
    "check_formal_stage_consistency": ToolCase(
        tool_name="check_formal_stage_consistency",
        status="implemented",
        category="decl_stage_formal_read",
        reason="Statement and proof consistency gates covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
    ),
    "record_statement_nl_review_passed": ToolCase(
        tool_name="record_statement_nl_review_passed",
        status="implemented",
        category="decl_stage_statement_nl_review_mark_write",
        reason="Statement NL stage-specific passed mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_reviewer",
        agent_type="StatementNLReviewerAgent",
        restore_policy="checkpoint",
    ),
    "record_statement_nl_review_rejected": ToolCase(
        tool_name="record_statement_nl_review_rejected",
        status="implemented",
        category="decl_stage_statement_nl_review_mark_write",
        reason="Statement NL stage-specific rejected mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_reviewer",
        agent_type="StatementNLReviewerAgent",
        restore_policy="checkpoint",
    ),
    "record_statement_formal_review_passed": ToolCase(
        tool_name="record_statement_formal_review_passed",
        status="implemented",
        category="decl_stage_statement_formal_review_mark_write",
        reason="Statement Formal stage-specific passed semantic mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_reviewer",
        agent_type="StatementFormalReviewerAgent",
        restore_policy="checkpoint",
    ),
    "record_statement_formal_review_rejected": ToolCase(
        tool_name="record_statement_formal_review_rejected",
        status="implemented",
        category="decl_stage_statement_formal_review_mark_write",
        reason="Statement Formal stage-specific rejected semantic mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_reviewer",
        agent_type="StatementFormalReviewerAgent",
        restore_policy="checkpoint",
    ),
    "record_proof_nl_review_passed": ToolCase(
        tool_name="record_proof_nl_review_passed",
        status="implemented",
        category="decl_stage_proof_nl_review_mark_write",
        reason="Proof NL stage-specific passed semantic mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_reviewer",
        agent_type="ProofNLReviewerAgent",
        restore_policy="checkpoint",
    ),
    "record_proof_nl_review_rejected": ToolCase(
        tool_name="record_proof_nl_review_rejected",
        status="implemented",
        category="decl_stage_proof_nl_review_mark_write",
        reason="Proof NL stage-specific rejected semantic mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_nl_reviewer",
        agent_type="ProofNLReviewerAgent",
        restore_policy="checkpoint",
    ),
    "record_proof_formal_review_passed": ToolCase(
        tool_name="record_proof_formal_review_passed",
        status="implemented",
        category="decl_stage_proof_formal_review_mark_write",
        reason="Proof Formal stage-specific passed semantic mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_formal_reviewer",
        agent_type="ProofFormalReviewerAgent",
        restore_policy="checkpoint",
    ),
    "record_proof_formal_review_rejected": ToolCase(
        tool_name="record_proof_formal_review_rejected",
        status="implemented",
        category="decl_stage_proof_formal_review_mark_write",
        reason="Proof Formal stage-specific rejected semantic mark write covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_formal_reviewer",
        agent_type="ProofFormalReviewerAgent",
        restore_policy="checkpoint",
    ),
    "inspect_current_stage_review_status": ToolCase(
        tool_name="inspect_current_stage_review_status",
        status="implemented",
        category="decl_stage_review_status_read",
        reason="Reviewer status read covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_nl_reviewer",
        agent_type="StatementNLReviewerAgent",
        restore_policy="checkpoint",
    ),
    "run_decl_round_local_audit": ToolCase(
        tool_name="run_decl_round_local_audit",
        status="implemented",
        category="decl_graph_read_current",
        reason="Current decl round local audit covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_formal_worker",
        agent_type="ProofFormalWorkerAgent",
    ),
    "run_lean_file_diagnostics": ToolCase(
        tool_name="run_lean_file_diagnostics",
        status="implemented",
        category="statement_formal_diagnostics_read",
        reason="Real Lake diagnostics covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
    ),
    "scan_lean_sorry_axiom": ToolCase(
        tool_name="scan_lean_sorry_axiom",
        status="implemented",
        category="statement_formal_diagnostics_read",
        reason="Formal policy token scan covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
    ),
    "check_statement_formal_policy": ToolCase(
        tool_name="check_statement_formal_policy",
        status="implemented",
        category="statement_formal_diagnostics_read",
        reason="Statement formal policy check covered by strict real Lake DeclStage ToolSweep.",
        view_key="statement_formal_worker",
        agent_type="StatementFormalWorkerAgent",
    ),
    "check_proof_formal_policy": ToolCase(
        tool_name="check_proof_formal_policy",
        status="implemented",
        category="proof_formal_diagnostics_read",
        reason="Proof formal policy check covered by strict real Lake DeclStage ToolSweep.",
        view_key="proof_formal_worker",
        agent_type="ProofFormalWorkerAgent",
    ),
    "ensure_current_decl_graph": ToolCase(
        tool_name="ensure_current_decl_graph",
        status="implemented",
        category="decl_graph_store_write",
        reason="Checkpointed DeclGraph store ensure covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "get_current_decl_graph_index": ToolCase(
        tool_name="get_current_decl_graph_index",
        status="implemented",
        category="decl_graph_read_current",
        reason="DeclGraph index read covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "get_current_decl_graph_store": ToolCase(
        tool_name="get_current_decl_graph_store",
        status="implemented",
        category="decl_graph_read_current",
        reason="DeclGraph store view read covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "rebuild_current_decl_graph_index": ToolCase(
        tool_name="rebuild_current_decl_graph_index",
        status="implemented",
        category="decl_graph_store_write",
        reason="Checkpointed DeclGraph index rebuild covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "ensure_open_decl_strategy": ToolCase(
        tool_name="ensure_open_decl_strategy",
        status="implemented",
        category="decl_strategy_write",
        reason="Checkpointed open strategy ensure covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "close_decl_strategy": ToolCase(
        tool_name="close_decl_strategy",
        status="implemented",
        category="decl_strategy_write",
        reason="Checkpointed strategy close covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "list_decl_strategies": ToolCase(
        tool_name="list_decl_strategies",
        status="implemented",
        category="decl_graph_read_current",
        reason="Strategy list read covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "get_decl_strategy": ToolCase(
        tool_name="get_decl_strategy",
        status="implemented",
        category="decl_graph_read_current",
        reason="Strategy lookup covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "create_decl_round_draft": ToolCase(
        tool_name="create_decl_round_draft",
        status="implemented",
        category="decl_round_change_write",
        reason="Checkpointed round draft creation covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "list_decl_rounds": ToolCase(
        tool_name="list_decl_rounds",
        status="implemented",
        category="decl_graph_read_current",
        reason="Round list read covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "get_decl_round": ToolCase(
        tool_name="get_decl_round",
        status="implemented",
        category="decl_graph_read_current",
        reason="Round lookup covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "write_decl_change_summary": ToolCase(
        tool_name="write_decl_change_summary",
        status="implemented",
        category="decl_round_closeout_write",
        reason="Checkpointed change summary write covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "write_decl_round_summary": ToolCase(
        tool_name="write_decl_round_summary",
        status="implemented",
        category="decl_round_closeout_write",
        reason="Checkpointed round summary write covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "mark_decl_round_terminal": ToolCase(
        tool_name="mark_decl_round_terminal",
        status="implemented",
        category="decl_round_closeout_write",
        reason="Checkpointed round terminal mark covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "plan_create_decl": ToolCase(
        tool_name="plan_create_decl",
        status="implemented",
        category="decl_catalog_plan_write",
        reason="Checkpointed declaration create planning covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "plan_update_decl": ToolCase(
        tool_name="plan_update_decl",
        status="implemented",
        category="decl_catalog_plan_write",
        reason="Checkpointed declaration update planning covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "plan_delete_decl": ToolCase(
        tool_name="plan_delete_decl",
        status="implemented",
        category="decl_catalog_plan_write",
        reason="Checkpointed declaration delete planning covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "list_current_node_decls": ToolCase(
        tool_name="list_current_node_decls",
        status="implemented",
        category="current_node_decl_read",
        reason="Current-node declaration list read covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "inspect_current_node_decl": ToolCase(
        tool_name="inspect_current_node_decl",
        status="implemented",
        category="current_node_decl_read",
        reason="Current-node declaration inspection covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "preview_decl_delete_closure": ToolCase(
        tool_name="preview_decl_delete_closure",
        status="implemented",
        category="decl_round_change_write",
        reason="Delete closure preview covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "validate_decl_round_draft": ToolCase(
        tool_name="validate_decl_round_draft",
        status="implemented",
        category="decl_round_change_write",
        reason="Round draft validation covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "compute_current_node_decl_dependency_closure": ToolCase(
        tool_name="compute_current_node_decl_dependency_closure",
        status="implemented",
        category="decl_dependency_analysis_read",
        reason="Current-node dependency closure read covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "list_active_decl_names": ToolCase(
        tool_name="list_active_decl_names",
        status="implemented",
        category="decl_graph_read_current",
        reason="Active declaration name list covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "check_current_content_node_completion": ToolCase(
        tool_name="check_current_content_node_completion",
        status="implemented",
        category="content_completion_gate_read",
        reason="Current content-node completion gate covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
    "bind_current_node_interface": ToolCase(
        tool_name="bind_current_node_interface",
        status="implemented",
        category="content_interface_current_write",
        reason="Checkpointed current Content interface binding covered by strict DeclGraph ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
        restore_policy="checkpoint",
    ),
    "get_current_repo_completion_policy": ToolCase(
        tool_name="get_current_repo_completion_policy",
        status="implemented",
        category="content_completion_gate_read",
        reason="Current repo work config covered by the standard strict application ToolSweep.",
        view_key="content_plan",
        agent_type="ContentPlanAgent",
    ),
}


ENV_GATED_GROUPS = {
    "upstream_navigation",
    "mathlib_semantic_search",
    "mathlib_navigation",
    "external_resource_discovery",
    "upstream_repo_search",
    "github_repository_read",
    "source_acquisition",
    "resource_acquisition",
}


def build_tool_cases() -> dict[str, ToolCase]:
    cases = dict(IMPLEMENTED_TOOL_CASES)
    for spec in build_application_tool_specs():
        if spec.name in cases:
            continue
        groups = set(spec.tool_groups)
        if groups & ENV_GATED_GROUPS:
            cases[spec.name] = ToolCase(
                tool_name=spec.name,
                status="pending_env",
                category="env_gated",
                reason="Requires live Toolkit, real network, GitHub, arXiv, or external repo visibility before it can count as complete.",
            )
        else:
            cases[spec.name] = ToolCase(
                tool_name=spec.name,
                status="pending_fixture",
                category="needs_strict_fixture",
                reason="Needs a dedicated strict fixture and concrete assertion before it can count as complete.",
            )
    return cases


def implemented_tool_cases() -> dict[str, ToolCase]:
    return {name: case for name, case in build_tool_cases().items() if case.implemented}


def pending_tool_cases() -> dict[str, ToolCase]:
    return {name: case for name, case in build_tool_cases().items() if not case.implemented}
