"""Canonical key catalogs for production ToolGroup and ToolView registries."""

from __future__ import annotations

from enum import StrEnum


class ApplicationToolGroupKey(StrEnum):
    ADAPTER_DECL_CATALOG_READ = "adapter_decl_catalog_read"
    ADAPTER_DECL_CATALOG_WRITE = "adapter_decl_catalog_write"
    ADAPTER_INPUT_READ = "adapter_input_read"
    ADAPTER_INTERFACE_BINDING_READ = "adapter_interface_binding_read"
    ADAPTER_INTERFACE_BINDING_WRITE = "adapter_interface_binding_write"
    ADAPTER_PROJECTION_CHECK = "adapter_projection_check"
    ADAPTER_PROJECTION_WRITE = "adapter_projection_write"
    ADAPTER_READY_READ = "adapter_ready_read"
    CONTENT_TASK_ADMISSION_READ = "content_task_admission_read"
    CONTENT_TASK_RESULT_COORDINATOR_FINALIZE = "content_task_result_coordinator_finalize"
    CONTENT_COMPLETION_GATE_READ = "content_completion_gate_read"
    DECL_CATALOG_PLAN_WRITE = "decl_catalog_plan_write"
    CURRENT_NODE_DECL_READ = "current_node_decl_read"
    DECL_DEPENDENCY_ANALYSIS_READ = "decl_dependency_analysis_read"
    DECL_DETAIL_READ = "decl_detail_read"
    DECL_GRAPH_CURRENT_WRITE = "decl_graph_current_write"
    DECL_GRAPH_READ_CURRENT = "decl_graph_read_current"
    DECL_HISTORY_READ = "decl_history_read"
    DECL_READINESS_READ = "decl_readiness_read"
    DECL_ROUND_CHANGE_WRITE = "decl_round_change_write"
    DECL_ROUND_CLOSEOUT_WRITE = "decl_round_closeout_write"
    DECL_STAGE_PROOF_FORMAL_FILE = "decl_stage_proof_formal_file"
    DECL_STAGE_PROOF_FORMAL_FILE_WRITE = "decl_stage_proof_formal_file_write"
    DECL_STAGE_PROOF_NL_WRITE = "decl_stage_proof_nl_write"
    DECL_STAGE_REVIEW_MARK_WRITE = "decl_stage_review_mark_write"
    DECL_STAGE_STATEMENT_FORMAL_FILE = "decl_stage_statement_formal_file"
    DECL_STAGE_STATEMENT_FORMAL_FILE_WRITE = "decl_stage_statement_formal_file_write"
    DECL_STAGE_STATEMENT_NL_WRITE = "decl_stage_statement_nl_write"
    DECL_STRATEGY_WRITE = "decl_strategy_write"
    EXTERNAL_RESOURCE_DISCOVERY = "external_resource_discovery"
    PROOF_FORMAL_DIAGNOSTICS_READ = "proof_formal_diagnostics_read"
    LAKE_DEPENDENCY_READ = "lake_dependency_read"
    LAKE_DEPENDENCY_WRITE = "lake_dependency_write"
    MATERIAL_CONTEXT_READ = "material_context_read"
    MATERIAL_ACQUISITION = "material_acquisition"
    MATHLIB_INDEX_READ = "mathlib_index_read"
    MATHLIB_INDEX_WRITE = "mathlib_index_write"
    MATHLIB_NAVIGATION = "mathlib_navigation"
    MATHLIB_SEMANTIC_SEARCH = "mathlib_semantic_search"
    NODE_BOUNDARY_READ_CURRENT = "node_boundary_read_current"
    NODE_VISIBILITY_READ_COORDINATOR = "node_visibility_read_coordinator"
    NODE_VISIBILITY_READ_CURRENT = "node_visibility_read_current"
    NODE_CONTRACT_CORE_COORDINATOR_WRITE = "node_contract_core_coordinator_write"
    NODE_CONTRACT_DEPENDENCY_COORDINATOR_WRITE = "node_contract_dependency_coordinator_write"
    NODE_CONTRACT_DEPENDENCY_CURRENT_WRITE = "node_contract_dependency_current_write"
    NODE_CONTRACT_MATERIAL_COORDINATOR_WRITE = "node_contract_material_coordinator_write"
    NODE_CONTRACT_MATERIAL_CURRENT_WRITE = "node_contract_material_current_write"
    NODE_CONTRACT_MATHLIB_COORDINATOR_WRITE = "node_contract_mathlib_coordinator_write"
    NODE_CONTRACT_READ_COORDINATOR = "node_contract_read_coordinator"
    NODE_CONTRACT_READ_CURRENT = "node_contract_read_current"
    NODE_MATHLIB_HINT_READ = "node_mathlib_hint_read"
    NODE_MATHLIB_HINT_WRITE = "node_mathlib_hint_write"
    NODE_TREE_COORDINATOR_READ = "node_tree_coordinator_read"
    NODE_TREE_COORDINATOR_WRITE = "node_tree_coordinator_write"
    REPO_PREPARATION_INPUT_READ = "repo_preparation_input_read"
    REPO_WORK_CONFIG_READ = "repo_work_config_read"
    REPO_READY_READ = "repo_ready_read"
    PUBLIC_DECL_READ_COORDINATOR = "public_decl_read_coordinator"
    PUBLIC_DECL_READ = "public_decl_read"
    RESOURCE_CURATION_CONTEXT_READ = "resource_curation_context_read"
    RESOURCE_DRAFT_WRITE = "resource_draft_write"
    RESOURCE_LIBRARY_READ = "resource_library_read"
    RESOURCE_TARGET_PREFLIGHT_READ = "resource_target_preflight_read"
    ROOT_INTERFACE_PREPARE_READ = "root_interface_prepare_read"
    SCOPE_CLOSE_READ = "scope_close_read"
    SCOPE_CONTRACT_COORDINATOR_COMMIT = "scope_contract_coordinator_commit"
    SCOPE_EXPORT_INTERFACE_READ = "scope_export_interface_read"
    SCOPE_EXPORT_INTERFACE_WRITE = "scope_export_interface_write"
    SOURCE_ACQUISITION = "source_acquisition"
    SOURCE_CORPUS_READ = "source_corpus_read"
    SOURCE_INDEX_COMMITTED_READ = "source_index_committed_read"
    SOURCE_INDEX_DRAFT_READ = "source_index_draft_read"
    SOURCE_INDEX_DRAFT_WRITE = "source_index_draft_write"
    SOURCE_MATERIAL_TEXT_READ = "source_material_text_read"
    STATEMENT_FORMAL_DIAGNOSTICS_READ = "statement_formal_diagnostics_read"
    UPSTREAM_METADATA_READ = "upstream_metadata_read"
    UPSTREAM_METADATA_WRITE = "upstream_metadata_write"
    UPSTREAM_NAVIGATION = "upstream_navigation"
    UPSTREAM_REPO_SEARCH = "upstream_repo_search"
    WORKSPACE_PROVIDER_CATALOG_READ = "workspace_provider_catalog_read"
    WORKSPACE_REPO_CATALOG_READ = "workspace_repo_catalog_read"
    WORKSPACE_REQUIREMENT_READ = "workspace_requirement_read"
    WORKSPACE_REQUIREMENT_WRITE = "workspace_requirement_write"


class SubmitToolGroupKey(StrEnum):
    ADAPTER_READY_SUBMIT = "adapter_ready_submit"
    CONTENT_COMPLETION_SUBMIT = "content_completion_submit"
    CONTENT_PLAN_SUBMIT = "content_plan_submit"
    COORDINATOR_SUBMIT = "coordinator_submit"
    DECL_STAGE_REVIEWER_SUBMIT = "decl_stage_reviewer_submit"
    DECL_STAGE_WORKER_SUBMIT = "decl_stage_worker_submit"
    MATHLIB_RECON_SUBMIT = "mathlib_recon_submit"
    NODE_DIR_DEPENDENCY_RECON_SUBMIT = "node_dir_dependency_recon_submit"
    REPO_FORMAT_DISCOVERY_SUBMIT = "repo_format_discovery_submit"
    RESOURCE_RECON_SUBMIT = "resource_recon_submit"
    RESOURCE_CURATOR_SUBMIT = "resource_curator_submit"
    RESOURCE_REQUEST_SUBMIT = "resource_request_submit"
    ROOT_INTERFACE_PREPARE_SUBMIT = "root_interface_prepare_submit"
    SOURCE_CORPUS_PREPARE_SUBMIT = "source_corpus_prepare_submit"
    SOURCE_INDEX_BUILDER_SUBMIT = "source_index_builder_submit"
    SOURCE_INDEX_REVIEWER_SUBMIT = "source_index_reviewer_submit"


class ApplicationToolViewKey(StrEnum):
    REPO_FORMAT_DISCOVERY = "repo_format_discovery"
    SOURCE_CORPUS_PREPARE = "source_corpus_prepare"
    SOURCE_INDEX_BUILDER = "source_index_builder"
    SOURCE_INDEX_REVIEWER = "source_index_reviewer"
    ROOT_INTERFACE_PREPARE = "root_interface_prepare"
    ADAPTER_REPO_IMPORT = "adapter_repo_import"
    RESOURCE_CURATOR = "resource_curator"
    NATIVE_REPO_COORDINATOR = "native_repo_coordinator"
    CONTENT_PLAN = "content_plan"
    NODE_DIR_DEPENDENCY_RECON = "node_dir_dependency_recon"
    MATHLIB_RECON = "mathlib_recon"
    RESOURCE_RECON = "resource_recon"
    STATEMENT_NL_WORKER = "statement_nl_worker"
    STATEMENT_FORMAL_WORKER = "statement_formal_worker"
    PROOF_NL_WORKER = "proof_nl_worker"
    PROOF_FORMAL_WORKER = "proof_formal_worker"
    STATEMENT_NL_REVIEWER = "statement_nl_reviewer"
    STATEMENT_FORMAL_REVIEWER = "statement_formal_reviewer"
    PROOF_NL_REVIEWER = "proof_nl_reviewer"
    PROOF_FORMAL_REVIEWER = "proof_formal_reviewer"


class SubmitToolViewKey(StrEnum):
    REPO_FORMAT_DISCOVERY_SUBMIT = "repo_format_discovery_submit"
    SOURCE_CORPUS_PREPARE_SUBMIT = "source_corpus_prepare_submit"
    SOURCE_INDEX_BUILDER_SUBMIT = "source_index_builder_submit"
    SOURCE_INDEX_REVIEWER_SUBMIT = "source_index_reviewer_submit"
    ROOT_INTERFACE_PREPARE_SUBMIT = "root_interface_prepare_submit"
    ADAPTER_REPO_IMPORT_SUBMIT = "adapter_repo_import_submit"
    RESOURCE_CURATOR_SUBMIT = "resource_curator_submit"
    NATIVE_REPO_COORDINATOR_SUBMIT = "native_repo_coordinator_submit"
    CONTENT_PLAN_SUBMIT = "content_plan_submit"
    NODE_DIR_DEPENDENCY_RECON_SUBMIT = "node_dir_dependency_recon_submit"
    MATHLIB_RECON_SUBMIT = "mathlib_recon_submit"
    RESOURCE_RECON_SUBMIT = "resource_recon_submit"
    DECL_STAGE_WORKER_SUBMIT = "decl_stage_worker_submit"
    DECL_STAGE_REVIEWER_SUBMIT = "decl_stage_reviewer_submit"


__all__ = [
    "ApplicationToolGroupKey",
    "ApplicationToolViewKey",
    "SubmitToolGroupKey",
    "SubmitToolViewKey",
]
