"""Adapter repo catalog and upstream navigation tools."""

from __future__ import annotations

from lean_constellation.services.tool_facade import ToolCapability, ToolSpec
from lean_constellation.tools.args import (
    AdapterDeclCreateArgs,
    AdapterDeclListArgs,
    AdapterDeclNameArgs,
    AdapterDeclOptionalNameArgs,
    AdapterDeclUpstreamFindArgs,
    AdapterDepArgs,
    AdapterDepRemoveArgs,
    AdapterFormalArgs,
    AdapterInterfaceBindArgs,
    AdapterInterfaceUnbindArgs,
    AdapterNlArgs,
    AdapterOriginArgs,
    AdapterUpstreamMetadataArgs,
    AdapterVisibleModulesArgs,
    NoArgs,
    QueryLimitArgs,
    SummaryArgs,
    UpstreamCaptureArgs,
    UpstreamDeclInspectArgs,
    UpstreamDeclSearchArgs,
    UpstreamModuleDeclsArgs,
    UpstreamModuleArgs,
    UpstreamSourceContextArgs,
)
from lean_constellation.tools.keys import ApplicationToolGroupKey as AppGroup
from lean_constellation.tools.specs import direct_tool


def build_tool_specs() -> list[ToolSpec]:
    roles = {"coordinator", "worker", "reviewer", "admin"}
    write_roles = {"worker", "admin"}
    return [
        direct_tool(
            name="inspect_adapter_input",
            description="Read adapter preparation input and expected interfaces.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="inspect_adapter_input",
            result_view="adapter_input",
            groups={AppGroup.ADAPTER_INPUT_READ},
            roles=roles,
        ),
        direct_tool(
            name="get_adapter_upstream_metadata",
            description="Read adapter upstream metadata.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="get_adapter_upstream_metadata",
            result_view="adapter_upstream",
            groups={AppGroup.UPSTREAM_METADATA_READ},
            roles=roles,
        ),
        direct_tool(
            name="get_adapter_upstream_status",
            description="Read adapter upstream build and module visibility status.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="get_adapter_upstream_status",
            result_view="adapter_upstream_status",
            groups={AppGroup.UPSTREAM_METADATA_READ},
            roles=roles,
        ),
        direct_tool(
            name="write_adapter_upstream_metadata",
            description="Write adapter upstream repo metadata after setup or discovery.",
            args_model=AdapterUpstreamMetadataArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="write_adapter_upstream_metadata",
            result_view="adapter_upstream",
            groups={AppGroup.UPSTREAM_METADATA_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="mark_upstream_build_trusted",
            description="Record that the upstream build was checked and trusted.",
            args_model=SummaryArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="mark_upstream_build_trusted",
            result_view="adapter_upstream",
            groups={AppGroup.UPSTREAM_METADATA_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="record_visible_upstream_modules",
            description="Record visible upstream modules for adapter discovery.",
            args_model=AdapterVisibleModulesArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="record_visible_upstream_modules",
            result_view="adapter_upstream",
            groups={AppGroup.UPSTREAM_METADATA_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="search_upstream_declarations",
            description="Search declarations in the adapter upstream Lean repo.",
            args_model=UpstreamDeclSearchArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="search_upstream_declarations",
            result_view="upstream_decl_search",
            groups={AppGroup.UPSTREAM_NAVIGATION},
            roles=roles,
        ),
        direct_tool(
            name="search_upstream_modules",
            description="Search modules in the adapter upstream Lean repo.",
            args_model=QueryLimitArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="search_upstream_modules",
            result_view="upstream_module_search",
            groups={AppGroup.UPSTREAM_NAVIGATION},
            roles=roles,
        ),
        direct_tool(
            name="list_upstream_module_declarations",
            description="List declarations in one upstream module.",
            args_model=UpstreamModuleDeclsArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="list_upstream_module_declarations",
            result_view="upstream_module_decls",
            groups={AppGroup.UPSTREAM_NAVIGATION},
            roles=roles,
        ),
        direct_tool(
            name="inspect_upstream_declaration",
            description="Inspect one upstream declaration.",
            args_model=UpstreamDeclInspectArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="inspect_upstream_declaration",
            result_view="upstream_decl_detail",
            groups={AppGroup.UPSTREAM_NAVIGATION},
            roles=roles,
        ),
        direct_tool(
            name="read_upstream_source_context",
            description="Read upstream source context around a module or declaration.",
            args_model=UpstreamSourceContextArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="read_upstream_source_context",
            result_view="upstream_source_context",
            groups={AppGroup.UPSTREAM_NAVIGATION},
            roles=roles,
        ),
        direct_tool(
            name="capture_upstream_declaration_code",
            description="Capture upstream declaration code for adapter declaration fields.",
            args_model=UpstreamCaptureArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="capture_upstream_declaration_code",
            result_view="upstream_capture",
            groups={AppGroup.UPSTREAM_NAVIGATION},
            roles=roles,
        ),
        direct_tool(
            name="inspect_upstream_module_imports",
            description="Inspect imports of one upstream module.",
            args_model=UpstreamModuleArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="inspect_upstream_module_imports",
            result_view="upstream_module_imports",
            groups={AppGroup.UPSTREAM_NAVIGATION},
            roles=roles,
        ),
        direct_tool(
            name="ensure_adapter_decl_catalog",
            description="Ensure the flat Main adapter declaration catalog exists.",
            args_model=NoArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="ensure_flat_main_catalog",
            result_view="adapter_catalog_init",
            groups={AppGroup.ADAPTER_DECL_CATALOG_INIT_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="create_adapter_decl",
            description="Create an adapter declaration catalog entry.",
            args_model=AdapterDeclCreateArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="create_adapter_decl",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="set_adapter_statement_formal",
            description="Set adapter declaration formal statement code.",
            args_model=AdapterFormalArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="set_adapter_statement_formal",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="set_adapter_statement_nl",
            description="Set adapter declaration natural-language statement.",
            args_model=AdapterNlArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="set_adapter_statement_nl",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="add_adapter_statement_origin",
            description="Add statement origin text to an adapter declaration.",
            args_model=AdapterOriginArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="add_adapter_statement_origin",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="add_adapter_statement_dep",
            description="Add a statement dependency to an adapter declaration.",
            args_model=AdapterDepArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="add_adapter_statement_dep",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="remove_adapter_statement_dep",
            description="Remove a statement dependency from an adapter declaration.",
            args_model=AdapterDepRemoveArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="remove_adapter_statement_dep",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="set_adapter_proof_formal",
            description="Set adapter declaration formal proof code.",
            args_model=AdapterFormalArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="set_adapter_proof_formal",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="set_adapter_proof_nl",
            description="Set adapter declaration natural-language proof.",
            args_model=AdapterNlArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="set_adapter_proof_nl",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="add_adapter_proof_origin",
            description="Add proof origin text to an adapter declaration.",
            args_model=AdapterOriginArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="add_adapter_proof_origin",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="add_adapter_proof_dep",
            description="Add a proof dependency to an adapter declaration.",
            args_model=AdapterDepArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="add_adapter_proof_dep",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="remove_adapter_proof_dep",
            description="Remove a proof dependency from an adapter declaration.",
            args_model=AdapterDepRemoveArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="remove_adapter_proof_dep",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="list_adapter_decls",
            description="List adapter declarations with optional filters.",
            args_model=AdapterDeclListArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="list_adapter_decls",
            result_view="adapter_decl_list",
            groups={AppGroup.ADAPTER_DECL_CATALOG_READ},
            roles=roles,
        ),
        direct_tool(
            name="inspect_adapter_decl",
            description="Inspect one adapter declaration.",
            args_model=AdapterDeclNameArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="inspect_adapter_decl",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_READ},
            roles=roles,
        ),
        direct_tool(
            name="list_registered_adapter_modules",
            description="List upstream modules represented in the adapter declaration catalog.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="list_registered_adapter_modules",
            result_view="adapter_modules",
            groups={AppGroup.ADAPTER_DECL_CATALOG_READ},
            roles=roles,
        ),
        direct_tool(
            name="check_adapter_decl_completeness",
            description="Check whether one or all adapter declarations have required fields.",
            args_model=AdapterDeclOptionalNameArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="check_adapter_decl_completeness",
            result_view="adapter_decl_completeness",
            groups={AppGroup.ADAPTER_DECL_CATALOG_READ},
            roles=roles,
        ),
        direct_tool(
            name="find_adapter_decl_by_upstream",
            description="Find existing adapter declarations for an upstream module and optional upstream declaration/name query.",
            args_model=AdapterDeclUpstreamFindArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="find_adapter_decl_by_upstream",
            result_view="adapter_decl_match",
            groups={AppGroup.ADAPTER_DECL_CATALOG_READ},
            roles=roles,
        ),
        direct_tool(
            name="finalize_adapter_decl",
            description="Finalize one complete adapter declaration entry.",
            args_model=AdapterDeclNameArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="finalize_adapter_decl",
            result_view="adapter_decl",
            groups={AppGroup.ADAPTER_DECL_CATALOG_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="bind_adapter_interface",
            description="Bind a preparation interface to an adapter declaration.",
            args_model=AdapterInterfaceBindArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="bind_adapter_interface",
            result_view="adapter_interface_binding",
            groups={AppGroup.ADAPTER_INTERFACE_BINDING_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="unbind_adapter_interface",
            description="Unbind an adapter interface.",
            args_model=AdapterInterfaceUnbindArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="unbind_adapter_interface",
            result_view="adapter_interface_binding",
            groups={AppGroup.ADAPTER_INTERFACE_BINDING_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="list_unbound_adapter_interfaces",
            description="List required adapter interfaces that are not yet bound.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="list_unbound_adapter_interfaces",
            result_view="adapter_unbound_interfaces",
            groups={AppGroup.ADAPTER_INTERFACE_BINDING_READ},
            roles=roles,
        ),
        direct_tool(
            name="validate_adapter_interface_bindings",
            description="Validate adapter interface bindings.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="validate_adapter_interface_bindings",
            result_view="gate_report",
            groups={AppGroup.ADAPTER_INTERFACE_BINDING_READ},
            roles=roles,
        ),
        direct_tool(
            name="preview_adapter_import_modules",
            description="Preview modules that will be imported by the adapter facade.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="preview_adapter_import_modules",
            result_view="adapter_import_preview",
            groups={AppGroup.ADAPTER_PROJECTION_CHECK},
            roles=roles,
        ),
        direct_tool(
            name="refresh_adapter_projection",
            description="Regenerate adapter Interfaces.lean projection.",
            args_model=NoArgs,
            capability=ToolCapability.WRITE,
            backing_service="adapter",
            backing_method="refresh_adapter_projection",
            result_view="adapter_projection",
            groups={AppGroup.ADAPTER_PROJECTION_WRITE},
            roles=write_roles,
        ),
        direct_tool(
            name="check_adapter_projection",
            description="Check adapter projection consistency.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="check_adapter_projection",
            result_view="gate_report",
            groups={AppGroup.ADAPTER_PROJECTION_CHECK},
            roles=roles,
        ),
        direct_tool(
            name="check_adapter_ready",
            description="Check adapter ready gate without submitting.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="check_adapter_ready",
            result_view="gate_report",
            groups={AppGroup.ADAPTER_READY_READ},
            roles=roles,
        ),
        direct_tool(
            name="check_adapter_catalog_ready_preflight",
            description="Check adapter catalog readiness before submitting, excluding Flow-owned projection finalization.",
            args_model=NoArgs,
            capability=ToolCapability.READ,
            backing_service="adapter",
            backing_method="check_adapter_catalog_ready_preflight",
            result_view="gate_report",
            groups={AppGroup.ADAPTER_READY_READ},
            roles=roles,
        ),
    ]
