"""External client wrappers."""

from lean_constellation.services.external_clients.github_repo import (
    GitCheckoutResult,
    GitHubCodeSearchResult,
    GitHubLeanRepoProbeView,
    GitHubRepoCandidate,
    GitHubRepoClient,
    GitHubRepoClientConfig,
    GitHubRepoSearchResult,
    GitHubRepositoryFileView,
    GitHubRepositoryTreeView,
    GitHubTreeEntry,
    LeanRepoCandidateProbe,
)
from lean_constellation.services.external_clients.lake_command import (
    LakeCommandClient,
    LakeCommandClientConfig,
    LakeCommandSummaryView,
    LeanCheckSummaryView,
)
from lean_constellation.services.external_clients.mathlib_cache import MathlibCacheStats
from lean_constellation.services.external_clients.lean_mcp_toolkit import (
    LeanDiagnosticsResult,
    LeanMcpToolkitClient,
    LeanMcpToolkitClientConfig,
    MathlibSearchResult,
    SorryAxiomScanResult,
    ToolkitCatalogResult,
    ToolkitCallResult,
    ToolkitResponseWarning,
    ToolkitToolView,
)
from lean_constellation.services.external_clients.lean_toolchain import (
    LeanToolchainClient,
    LeanToolchainClientConfig,
    LeanToolchainProviderPolicy,
    ToolchainCommandView,
    ToolchainDeclarationView,
    ToolchainDiagnosticsView,
    ToolchainLeanCheckView,
    ToolchainMathlibSearchView,
    ToolchainModuleView,
    ToolchainPolicyOccurrenceView,
    ToolchainPolicyScanView,
    ToolchainToolCallView,
)
from lean_constellation.services.external_clients.material_acquisition import (
    AcquiredArtifactView,
    AcquiredArtifactResult,
    ExtractedMaterialResult,
    MaterialAcquisitionConfig,
    MaterialAcquisitionExtractionClient,
    MaterialTarget,
    ReadableTextValidationView,
    ResolvedArtifactKindView,
)
from lean_constellation.services.external_clients.process import ExternalCommandResult
from lean_constellation.services.external_clients.service import ExternalClientConfig, ExternalClientService
from lean_constellation.services.external_clients.resource_discovery import (
    ExternalResourceCandidate,
    ExternalResourceDiscoveryClient,
    ExternalResourceDiscoveryConfig,
    ExternalResourceInspectResult,
    ExternalResourceSearchResult,
)

__all__ = [
    "AcquiredArtifactResult",
    "AcquiredArtifactView",
    "ExternalClientConfig",
    "ExternalClientService",
    "ExternalResourceCandidate",
    "ExternalResourceDiscoveryClient",
    "ExternalResourceDiscoveryConfig",
    "ExternalResourceInspectResult",
    "ExternalResourceSearchResult",
    "ExternalCommandResult",
    "ExtractedMaterialResult",
    "GitCheckoutResult",
    "GitHubCodeSearchResult",
    "GitHubLeanRepoProbeView",
    "GitHubRepoCandidate",
    "GitHubRepoClient",
    "GitHubRepoClientConfig",
    "GitHubRepoSearchResult",
    "GitHubRepositoryFileView",
    "GitHubRepositoryTreeView",
    "GitHubTreeEntry",
    "LakeCommandClient",
    "LakeCommandClientConfig",
    "LakeCommandSummaryView",
    "LeanCheckSummaryView",
    "MathlibCacheStats",
    "LeanDiagnosticsResult",
    "LeanMcpToolkitClient",
    "LeanMcpToolkitClientConfig",
    "LeanRepoCandidateProbe",
    "LeanToolchainClient",
    "LeanToolchainClientConfig",
    "LeanToolchainProviderPolicy",
    "MaterialAcquisitionConfig",
    "MaterialAcquisitionExtractionClient",
    "MaterialTarget",
    "MathlibSearchResult",
    "ReadableTextValidationView",
    "ResolvedArtifactKindView",
    "SorryAxiomScanResult",
    "ToolkitCatalogResult",
    "ToolkitCallResult",
    "ToolchainCommandView",
    "ToolchainDeclarationView",
    "ToolchainDiagnosticsView",
    "ToolchainLeanCheckView",
    "ToolchainMathlibSearchView",
    "ToolchainModuleView",
    "ToolchainPolicyOccurrenceView",
    "ToolchainPolicyScanView",
    "ToolchainToolCallView",
    "ToolkitResponseWarning",
    "ToolkitToolView",
]
