from pathlib import Path

from lean_constellation.domain.refs import DeclRef
from lean_constellation.services.foundation import ServiceResult
from lean_constellation.services.foundation import FoundationContext, FoundationService, WriteMode
from lean_constellation.services.lean_projection import NodeProjectionComponent
from lean_constellation.services.node import DeclPublicView, ExportComponent, NodeContractSnapshot, NodeTreeComponent


class FakePublicDeclProvider:
    def __init__(self, foundation: FoundationService, decls: dict[str, list[DeclPublicView]]) -> None:
        self.foundation = foundation
        self.decls = decls

    def list_content_public_decls(self, repo_root: Path, *, node_path: str) -> ServiceResult[list[DeclPublicView]]:
        return self.foundation.ok(self.decls.get(node_path, []))


class FailingPublicDeclProvider:
    def __init__(self, foundation: FoundationService) -> None:
        self.foundation = foundation

    def list_content_public_decls(self, repo_root: Path, *, node_path: str) -> ServiceResult[list[DeclPublicView]]:
        del repo_root
        return self.foundation.fail(
            self.foundation.issue(
                "content_public_decl_provider_failed",
                "Public declaration provider failed.",
                object_ref=node_path,
            )
        )


def _create_nodes(tmp_path: Path) -> None:
    tree = NodeTreeComponent()
    assert tree.ensure_root_scope_node(tmp_path).ok
    assert tree.create_scope_node(tmp_path, path="Main.Topic", goal="Topic goal", boundary="Topic boundary").ok
    assert tree.create_scope_node(tmp_path, path="Main.Topic.Provider", goal="Provider goal", boundary="Provider boundary").ok
    assert tree.create_content_node(
        tmp_path,
        path="Main.Topic.Core",
        goal="Core goal",
        boundary="Core boundary",
        objective="Build core.",
        success_criteria="Core ready.",
    ).ok


def _update_core_contract(tmp_path: Path) -> None:
    foundation = FoundationService()
    ctx = FoundationContext(repo_root=tmp_path)
    path = foundation.node_contract_path(ctx, "Main.Topic.Core", 1)
    loaded = foundation.read_json(path, NodeContractSnapshot)
    assert loaded.ok and loaded.value is not None
    loaded.value.deps.extend(
        [
            {"target": {"repo": None, "node": "Main.Topic.Provider"}, "reason": "Use provider boundary."},
            {"target": {"repo": "OtherRepo", "node": "Main"}, "reason": "Use external repo boundary."},
            {"target": {"repo": None, "node": "Main.Topic.Core"}, "reason": "Self dependency should not import self."},
        ]
    )
    loaded.value.mathlib_modules.extend(
        [
            {"module": "Mathlib.Data.Finset.Basic", "reason": "Finite sums."},
            {"ref": {"module": "Mathlib.Topology.Basic"}, "reason": "Topology."},
            {"module": "Mathlib.Data.Finset.Basic", "reason": "Duplicate."},
        ]
    )
    saved = foundation.write_json_atomic(path, loaded.value, mode=WriteMode.UPDATE_EXISTING)
    assert saved.ok


def _core_contract(tmp_path: Path) -> NodeContractSnapshot:
    foundation = FoundationService()
    loaded = foundation.read_json(
        foundation.node_contract_path(FoundationContext(repo_root=tmp_path), "Main.Topic.Core", 1),
        NodeContractSnapshot,
    )
    assert loaded.ok and loaded.value is not None
    return loaded.value


def _save_core_contract(tmp_path: Path, snapshot: NodeContractSnapshot) -> None:
    foundation = FoundationService()
    saved = foundation.write_json_atomic(
        foundation.node_contract_path(FoundationContext(repo_root=tmp_path), "Main.Topic.Core", 1),
        snapshot,
        mode=WriteMode.UPDATE_EXISTING,
    )
    assert saved.ok


def test_render_prelude_from_node_deps_and_mathlib_modules(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    _update_core_contract(tmp_path)
    component = NodeProjectionComponent()

    rendered = component.render_prelude(tmp_path, node_path="Main.Topic.Core")

    assert rendered.ok
    assert rendered.value is not None
    assert "This file is generated by Lean Constellation." in rendered.value
    assert "Node: Main.Topic.Core" in rendered.value
    assert "import Main.Topic.Provider.Interfaces" in rendered.value
    assert "import OtherRepo.Main.Interfaces" in rendered.value
    assert "import Mathlib.Data.Finset.Basic" in rendered.value
    assert "import Mathlib.Topology.Basic" in rendered.value
    assert rendered.value.count("Mathlib.Data.Finset.Basic") == 1
    assert "import Main.Topic.Core.Interfaces" not in rendered.value


def test_render_prelude_rejects_invalid_import_module(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    snapshot = _core_contract(tmp_path)
    snapshot.mathlib_modules.append({"module": "Bad Module", "reason": "Invalid import."})
    _save_core_contract(tmp_path, snapshot)
    component = NodeProjectionComponent()

    rendered = component.render_prelude(tmp_path, node_path="Main.Topic.Core")

    assert not rendered.ok
    assert rendered.issues[0].kind == "prelude_import_invalid"


def test_refresh_prelude_changed_and_no_changed(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    _update_core_contract(tmp_path)
    component = NodeProjectionComponent()

    first = component.refresh_prelude(tmp_path, node_path="Main.Topic.Core")
    assert first.ok
    assert first.value is not None
    assert first.value.changed is True
    assert Path(first.value.path).exists()

    second = component.refresh_prelude(tmp_path, node_path="Main.Topic.Core")
    assert second.ok
    assert second.value is not None
    assert second.value.changed is False


def test_refresh_and_check_prelude_report_filesystem_errors(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    component = NodeProjectionComponent()
    path = tmp_path / "Main" / "Topic" / "Core" / "Prelude.lean"
    path.mkdir(parents=True)

    refresh = component.refresh_prelude(tmp_path, node_path="Main.Topic.Core")
    assert not refresh.ok
    assert refresh.issues[0].kind == "prelude_projection_write_failed"

    check = component.check_prelude_sync(tmp_path, node_path="Main.Topic.Core")
    assert not check.ok
    assert check.issues[0].kind == "prelude_projection_read_failed"


def test_check_prelude_sync_missing_synced_and_stale(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    _update_core_contract(tmp_path)
    component = NodeProjectionComponent()

    missing = component.check_prelude_sync(tmp_path, node_path="Main.Topic.Core")
    assert missing.ok
    assert missing.value is not None
    assert missing.value.passed is False
    assert missing.value.issues[0].kind == "prelude_projection_missing"

    refreshed = component.refresh_prelude(tmp_path, node_path="Main.Topic.Core")
    assert refreshed.ok and refreshed.value is not None

    synced = component.check_prelude_sync(tmp_path, node_path="Main.Topic.Core")
    assert synced.ok
    assert synced.value is not None
    assert synced.value.passed is True

    Path(refreshed.value.path).write_text("import Bad.Module\n", encoding="utf-8")
    stale = component.check_prelude_sync(tmp_path, node_path="Main.Topic.Core")
    assert stale.ok
    assert stale.value is not None
    assert stale.value.passed is False
    assert stale.value.issues[0].kind == "prelude_projection_stale"


def test_render_content_interfaces_from_public_decl_modules(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    foundation = FoundationService()
    provider = FakePublicDeclProvider(
        foundation,
        {
            "Main.Topic.Core": [
                DeclPublicView(
                    ref=DeclRef(repo=None, node="Main.Topic.Core", name="core_def", revision=1),
                    kind="definition",
                    summary="Core definition.",
                ),
                DeclPublicView(
                    ref=DeclRef(repo=None, node="Main.Topic.Core", name="main_result", revision=1),
                    kind="theorem",
                    summary="Main theorem.",
                ),
            ]
        },
    )
    export = ExportComponent(foundation=foundation, public_decl_provider=provider)
    component = NodeProjectionComponent(foundation=foundation, export=export)

    rendered = component.render_interfaces(tmp_path, node_path="Main.Topic.Core")

    assert rendered.ok
    assert rendered.value is not None
    assert "Node: Main.Topic.Core" in rendered.value
    assert "import Main.Topic.Core.Defs.core_def" in rendered.value
    assert "import Main.Topic.Core.Theorems.main_result" in rendered.value


def test_render_content_interfaces_rejects_provider_failure_cross_repo_and_not_ready(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    foundation = FoundationService()
    failing_export = ExportComponent(foundation=foundation, public_decl_provider=FailingPublicDeclProvider(foundation))
    failing = NodeProjectionComponent(foundation=foundation, export=failing_export)

    provider_failed = failing.render_interfaces(tmp_path, node_path="Main.Topic.Core")
    assert not provider_failed.ok
    assert provider_failed.issues[0].kind == "content_public_decl_provider_failed"

    cross_repo_provider = FakePublicDeclProvider(
        foundation,
        {
            "Main.Topic.Core": [
                DeclPublicView(
                    ref=DeclRef(repo="OtherRepo", node="Main", name="external_decl", revision=1),
                    kind="theorem",
                    summary="External theorem.",
                )
            ]
        },
    )
    cross_repo = NodeProjectionComponent(
        foundation=foundation,
        export=ExportComponent(foundation=foundation, public_decl_provider=cross_repo_provider),
    ).render_interfaces(tmp_path, node_path="Main.Topic.Core")
    assert not cross_repo.ok
    assert cross_repo.issues[0].kind == "interfaces_decl_cross_repo_unsupported"

    not_ready_provider = FakePublicDeclProvider(
        foundation,
        {
            "Main.Topic.Core": [
                DeclPublicView(
                    ref=DeclRef(repo=None, node="Main.Topic.Core", name="main_result", revision=1),
                    kind="theorem",
                    summary="Main theorem.",
                    ready=False,
                ),
                DeclPublicView(
                    ref=DeclRef(repo=None, node="Main.Topic.Core", name="old_result", revision=1),
                    kind="theorem",
                    summary="Old theorem.",
                    stale=True,
                ),
            ]
        },
    )
    not_ready = NodeProjectionComponent(
        foundation=foundation,
        export=ExportComponent(foundation=foundation, public_decl_provider=not_ready_provider),
    ).render_interfaces(tmp_path, node_path="Main.Topic.Core")
    assert not not_ready.ok
    assert not_ready.issues[0].kind == "interfaces_decl_not_ready"


def test_refresh_and_check_interfaces_report_filesystem_errors(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    component = NodeProjectionComponent()
    path = tmp_path / "Main" / "Topic" / "Core" / "Interfaces.lean"
    path.mkdir(parents=True)

    refresh = component.refresh_interfaces(tmp_path, node_path="Main.Topic.Core")
    assert not refresh.ok
    assert refresh.issues[0].kind == "interfaces_projection_write_failed"

    check = component.check_interfaces_sync(tmp_path, node_path="Main.Topic.Core")
    assert not check.ok
    assert check.issues[0].kind == "interfaces_projection_read_failed"


def test_refresh_and_check_scope_interfaces_from_exports(tmp_path: Path) -> None:
    _create_nodes(tmp_path)
    foundation = FoundationService()
    provider = FakePublicDeclProvider(
        foundation,
        {
            "Main.Topic.Core": [
                DeclPublicView(
                    ref=DeclRef(repo=None, node="Main.Topic.Core", name="main_result", revision=1),
                    kind="theorem",
                    summary="Main theorem.",
                )
            ]
        },
    )
    export = ExportComponent(foundation=foundation, public_decl_provider=provider)
    component = NodeProjectionComponent(foundation=foundation, export=export)

    missing = component.check_interfaces_sync(tmp_path, node_path="Main.Topic")
    assert missing.ok
    assert missing.value is not None
    assert missing.value.passed is False
    assert missing.value.issues[0].kind == "interfaces_projection_missing"

    added = export.add_scope_export(tmp_path, scope_path="Main.Topic", decl_ref="Main.Topic.Core:main_result")
    assert added.ok

    synced = component.check_interfaces_sync(tmp_path, node_path="Main.Topic")
    assert synced.ok
    assert synced.value is not None
    assert synced.value.passed is True
    path = tmp_path / "Main" / "Topic" / "Interfaces.lean"
    assert "import Main.Topic.Core.Theorems.main_result" in path.read_text(encoding="utf-8")

    path.write_text("import Bad.Module\n", encoding="utf-8")
    stale = component.check_interfaces_sync(tmp_path, node_path="Main.Topic")
    assert stale.ok
    assert stale.value is not None
    assert stale.value.passed is False
    assert stale.value.issues[0].kind == "interfaces_projection_stale"
