"""Adapter repo Main.Interfaces projection."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Protocol

from pydantic import Field

from lean_constellation.domain.common import StrictModel
from lean_constellation.services.foundation import FoundationContext, GateReport, ServiceResult
from lean_constellation.services.lean_projection.node_projection import ProjectionView

if TYPE_CHECKING:
    from lean_constellation.services.runtime import LeanRuntimeServices


class AdapterModuleListView(StrictModel):
    modules: list[str] = Field(default_factory=list)
    summary: str


class AdapterFacadeProvider(Protocol):
    """Provider for adapter active decl modules and upstream visibility."""

    def list_active_adapter_modules(self, repo_root: Path) -> ServiceResult[AdapterModuleListView]:
        ...

    def list_visible_upstream_modules(self, repo_root: Path) -> ServiceResult[AdapterModuleListView]:
        ...


class _MissingAdapterFacadeProvider:
    def __init__(self, runtime: LeanRuntimeServices) -> None:
        self.runtime = runtime

    def list_active_adapter_modules(self, repo_root: Path) -> ServiceResult[AdapterModuleListView]:
        del repo_root
        return self.runtime.foundation.fail(
            self.runtime.foundation.issue(
                "adapter_facade_provider_missing",
                "No adapter facade provider is configured.",
            )
        )

    def list_visible_upstream_modules(self, repo_root: Path) -> ServiceResult[AdapterModuleListView]:
        return self.list_active_adapter_modules(repo_root)


class AdapterFacadeComponent:
    """Render, refresh, and check adapter `Main/Interfaces.lean`."""

    _HEADER = "/-\nThis file is generated by Lean Constellation.\nDo not edit manually.\nAdapter facade: Main.Interfaces\n-/\n"

    def __init__(
        self,
        runtime: LeanRuntimeServices,
        *,
        provider: AdapterFacadeProvider | None = None,
    ) -> None:
        self.runtime = runtime
        self.provider = provider or _MissingAdapterFacadeProvider(runtime)

    def render_adapter_interfaces(self, repo_root: Path) -> ServiceResult[str]:
        modules = self._active_modules(repo_root)
        if not modules.ok or modules.value is None:
            return self.runtime.foundation.fail(modules.issues)
        visibility = self._validate_modules_visible(repo_root, modules.value)
        if not visibility.ok or visibility.value is None:
            return self.runtime.foundation.fail(visibility.issues)
        if not visibility.value.passed:
            return self.runtime.foundation.fail(visibility.value.issues)
        lines = [self._HEADER.rstrip(), ""]
        lines.extend(f"public import {module}" for module in modules.value)
        return self.runtime.foundation.ok("\n".join(lines).rstrip() + "\n")

    def refresh_adapter_interfaces(self, repo_root: Path) -> ServiceResult[ProjectionView]:
        rendered = self.render_adapter_interfaces(repo_root)
        if not rendered.ok or rendered.value is None:
            return self.runtime.foundation.fail(rendered.issues)
        path = self._interfaces_path(repo_root)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            old_text = path.read_text(encoding="utf-8") if path.exists() else None
            changed = old_text != rendered.value
            if changed:
                path.write_text(rendered.value, encoding="utf-8")
        except OSError as exc:
            return self.runtime.foundation.fail(
                self.runtime.foundation.issue(
                    "adapter_interfaces_write_failed",
                    f"Failed to write adapter Main/Interfaces.lean: {exc}",
                    details={"path": str(path)},
                )
            )
        return self.runtime.foundation.ok(
            ProjectionView(
                node_path="Main",
                projection_kind="interfaces",
                path=str(path),
                changed=changed,
                line_count=len(rendered.value.splitlines()),
                summary=("Updated adapter Main/Interfaces.lean." if changed else "Adapter Main/Interfaces.lean is already synchronized."),
            )
        )

    def check_adapter_module_visible(self, repo_root: Path, *, module: str) -> ServiceResult[GateReport]:
        normalized = self._normalize_module(module)
        if normalized is None:
            return self.runtime.foundation.fail(
                self.runtime.foundation.issue(
                    "adapter_module_invalid",
                    "Adapter module must be a safe Lean module name.",
                    field="module",
                    current=module,
                )
            )
        visible = self.provider.list_visible_upstream_modules(Path(repo_root))
        if not visible.ok or visible.value is None:
            return self.runtime.foundation.fail(visible.issues)
        visible_modules = set(self._normalize_modules(visible.value.modules))
        if normalized not in visible_modules:
            return self.runtime.foundation.ok(
                self.runtime.foundation.gate_failed(
                    "adapter_module_visible",
                    self.runtime.foundation.issue(
                        "adapter_module_not_visible",
                        "Adapter module is not in the upstream visible module set.",
                        object_ref=normalized,
                        field="module",
                    ),
                    summary="Adapter module is not visible from the configured upstream dependency.",
                )
            )
        return self.runtime.foundation.ok(
            self.runtime.foundation.gate_passed(
                "adapter_module_visible",
                summary=f"Adapter module is visible: {normalized}.",
            )
        )

    def check_adapter_interfaces_sync(self, repo_root: Path) -> ServiceResult[GateReport]:
        rendered = self.render_adapter_interfaces(repo_root)
        if not rendered.ok or rendered.value is None:
            return self.runtime.foundation.fail(rendered.issues)
        path = self._interfaces_path(repo_root)
        if not path.exists():
            return self.runtime.foundation.ok(
                self.runtime.foundation.gate_failed(
                    "adapter_interfaces_sync",
                    self.runtime.foundation.issue(
                        "adapter_interfaces_missing",
                        "Generated adapter Main/Interfaces.lean is missing.",
                        details={"path": str(path)},
                    ),
                    summary="Generated adapter Main/Interfaces.lean is missing.",
                )
            )
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError as exc:
            return self.runtime.foundation.fail(
                self.runtime.foundation.issue(
                    "adapter_interfaces_read_failed",
                    f"Failed to read adapter Main/Interfaces.lean: {exc}",
                    details={"path": str(path)},
                )
            )
        if actual != rendered.value:
            return self.runtime.foundation.ok(
                self.runtime.foundation.gate_failed(
                    "adapter_interfaces_sync",
                    self.runtime.foundation.issue(
                        "adapter_interfaces_stale",
                        "Generated adapter Main/Interfaces.lean does not match active adapter modules.",
                        details={"path": str(path)},
                    ),
                    summary="Generated adapter Main/Interfaces.lean is stale.",
                )
            )
        return self.runtime.foundation.ok(
            self.runtime.foundation.gate_passed(
                "adapter_interfaces_sync",
                summary="Generated adapter Main/Interfaces.lean is synchronized.",
            )
        )

    def _active_modules(self, repo_root: Path) -> ServiceResult[list[str]]:
        active = self.provider.list_active_adapter_modules(Path(repo_root))
        if not active.ok or active.value is None:
            return self.runtime.foundation.fail(active.issues)
        modules = self._normalize_modules(active.value.modules)
        invalid = [module for module in active.value.modules if self._normalize_module(module) is None]
        if invalid:
            return self.runtime.foundation.fail(
                self.runtime.foundation.issue(
                    "adapter_active_module_invalid",
                    "Active adapter module list contains invalid Lean module names.",
                    current=", ".join(invalid),
                )
            )
        return self.runtime.foundation.ok(modules)

    def _validate_modules_visible(self, repo_root: Path, modules: list[str]) -> ServiceResult[GateReport]:
        visible = self.provider.list_visible_upstream_modules(Path(repo_root))
        if not visible.ok or visible.value is None:
            return self.runtime.foundation.fail(visible.issues)
        visible_modules = set(self._normalize_modules(visible.value.modules))
        missing = [module for module in modules if module not in visible_modules]
        if missing:
            return self.runtime.foundation.ok(
                self.runtime.foundation.gate_failed(
                    "adapter_modules_visible",
                    [
                        self.runtime.foundation.issue(
                            "adapter_module_not_visible",
                            "Active adapter module is not visible from the configured upstream dependency.",
                            object_ref=module,
                            field="module",
                        )
                        for module in missing
                    ],
                    summary=f"{len(missing)} active adapter modules are not visible.",
                )
            )
        return self.runtime.foundation.ok(
            self.runtime.foundation.gate_passed(
                "adapter_modules_visible",
                summary=f"{len(modules)} active adapter modules are visible.",
            )
        )

    def _interfaces_path(self, repo_root: Path) -> Path:
        return self.runtime.foundation.layout.adapter_interfaces_path(FoundationContext(repo_root=Path(repo_root)))

    def _normalize_modules(self, modules: list[str]) -> list[str]:
        normalized = [module for item in modules if (module := self._normalize_module(item)) is not None]
        return sorted(set(normalized))

    def _normalize_module(self, module: str) -> str | None:
        if not module or not module.strip():
            return None
        value = module.strip()
        if any(ch.isspace() for ch in value):
            return None
        if "/" in value or "\\" in value or ".." in value:
            return None
        if not all(part for part in value.split(".")):
            return None
        return value
