"""Node-level generated Lean projection files."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from pydantic import Field

from lean_constellation.domain.refs import DeclRef
from lean_constellation.domain.common import StrictModel
from lean_constellation.services.foundation import FoundationContext, FoundationService, GateReport, ServiceResult
from lean_constellation.services.node.contract import ContractComponent
from lean_constellation.services.node.export import ExportComponent, ScopeExportCandidate
from lean_constellation.services.node.node_tree import NodeKind


class ProjectionView(StrictModel):
    node_path: str
    projection_kind: Literal["prelude", "interfaces"]
    path: str
    changed: bool
    line_count: int
    summary: str


class NodeProjectionComponent:
    """Render, refresh, and check generated node projection files."""

    _HEADER = "/-\nThis file is generated by Lean Constellation.\nDo not edit manually.\nNode: {node_path}\n-/\n"

    def __init__(
        self,
        foundation: FoundationService | None = None,
        contract: ContractComponent | None = None,
        export: ExportComponent | None = None,
    ) -> None:
        self.foundation = foundation or FoundationService()
        self.contract = contract or ContractComponent(self.foundation)
        self.export = export or ExportComponent(self.foundation, contract=self.contract)

    def render_prelude(self, repo_root: Path, *, node_path: str) -> ServiceResult[str]:
        contract = self.contract.get_current_contract(repo_root, node_path=node_path)
        if not contract.ok or contract.value is None:
            return self.foundation.fail(contract.issues)
        imports = self._prelude_imports(node_path, contract.value.contract.deps, contract.value.contract.mathlib_modules)
        invalid = [module for module in imports if not self._is_safe_import_module(module)]
        if invalid:
            return self.foundation.fail(
                self.foundation.issue(
                    "prelude_import_invalid",
                    "Generated Prelude would contain invalid import modules.",
                    object_ref=node_path,
                    current=", ".join(invalid),
                )
            )
        lines = [self._HEADER.format(node_path=node_path).rstrip(), ""]
        lines.extend(f"import {module}" for module in imports)
        return self.foundation.ok("\n".join(lines).rstrip() + "\n")

    def refresh_prelude(self, repo_root: Path, *, node_path: str) -> ServiceResult[ProjectionView]:
        rendered = self.render_prelude(repo_root, node_path=node_path)
        if not rendered.ok or rendered.value is None:
            return self.foundation.fail(rendered.issues)
        path = self._prelude_path(repo_root, node_path)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            old_text = path.read_text(encoding="utf-8") if path.exists() else None
            changed = old_text != rendered.value
            if changed:
                path.write_text(rendered.value, encoding="utf-8")
        except OSError as exc:
            return self.foundation.fail(
                self.foundation.issue(
                    "prelude_projection_write_failed",
                    f"Failed to write generated Prelude.lean: {exc}",
                    object_ref=node_path,
                    details={"path": str(path)},
                )
            )
        return self.foundation.ok(
            ProjectionView(
                node_path=node_path,
                projection_kind="prelude",
                path=str(path),
                changed=changed,
                line_count=len(rendered.value.splitlines()),
                summary=("Updated generated Prelude.lean." if changed else "Generated Prelude.lean is already synchronized."),
            )
        )

    def check_prelude_sync(self, repo_root: Path, *, node_path: str) -> ServiceResult[GateReport]:
        rendered = self.render_prelude(repo_root, node_path=node_path)
        if not rendered.ok or rendered.value is None:
            return self.foundation.fail(rendered.issues)
        path = self._prelude_path(repo_root, node_path)
        if not path.exists():
            return self.foundation.ok(
                self.foundation.gate_failed(
                    "prelude_sync",
                    self.foundation.issue(
                        "prelude_projection_missing",
                        "Generated Prelude.lean is missing.",
                        object_ref=node_path,
                        details={"path": str(path)},
                    ),
                    summary="Generated Prelude.lean is missing.",
                )
            )
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError as exc:
            return self.foundation.fail(
                self.foundation.issue(
                    "prelude_projection_read_failed",
                    f"Failed to read generated Prelude.lean: {exc}",
                    object_ref=node_path,
                    details={"path": str(path)},
                )
            )
        if actual != rendered.value:
            return self.foundation.ok(
                self.foundation.gate_failed(
                    "prelude_sync",
                    self.foundation.issue(
                        "prelude_projection_stale",
                        "Generated Prelude.lean does not match current NodeContract deps/mathlib_modules.",
                        object_ref=node_path,
                        details={"path": str(path)},
                    ),
                    summary="Generated Prelude.lean is stale.",
                )
            )
        return self.foundation.ok(
            self.foundation.gate_passed(
                "prelude_sync",
                summary="Generated Prelude.lean is synchronized.",
            )
        )

    def render_interfaces(self, repo_root: Path, *, node_path: str) -> ServiceResult[str]:
        contract = self.contract.get_current_contract(repo_root, node_path=node_path)
        if not contract.ok or contract.value is None:
            return self.foundation.fail(contract.issues)
        if contract.value.node_kind == NodeKind.CONTENT:
            imports_result = self._content_interface_imports(repo_root, node_path=node_path)
        elif contract.value.node_kind == NodeKind.SCOPE:
            imports_result = self._scope_interface_imports(repo_root, scope_path=node_path)
        else:
            return self.foundation.fail(
                self.foundation.issue(
                    "interfaces_projection_node_kind_unsupported",
                    "Generated Interfaces.lean only supports Scope and Content nodes.",
                    object_ref=node_path,
                    current=str(contract.value.node_kind),
                )
            )
        if not imports_result.ok or imports_result.value is None:
            return self.foundation.fail(imports_result.issues)
        invalid = [module for module in imports_result.value if not self._is_safe_import_module(module)]
        if invalid:
            return self.foundation.fail(
                self.foundation.issue(
                    "interfaces_import_invalid",
                    "Generated Interfaces.lean would contain invalid import modules.",
                    object_ref=node_path,
                    current=", ".join(invalid),
                )
            )
        lines = [self._HEADER.format(node_path=node_path).rstrip(), ""]
        lines.extend(f"import {module}" for module in imports_result.value)
        return self.foundation.ok("\n".join(lines).rstrip() + "\n", warnings=imports_result.issues)

    def refresh_interfaces(self, repo_root: Path, *, node_path: str) -> ServiceResult[ProjectionView]:
        rendered = self.render_interfaces(repo_root, node_path=node_path)
        if not rendered.ok or rendered.value is None:
            return self.foundation.fail(rendered.issues)
        path = self._interfaces_path(repo_root, node_path)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            old_text = path.read_text(encoding="utf-8") if path.exists() else None
            changed = old_text != rendered.value
            if changed:
                path.write_text(rendered.value, encoding="utf-8")
        except OSError as exc:
            return self.foundation.fail(
                self.foundation.issue(
                    "interfaces_projection_write_failed",
                    f"Failed to write generated Interfaces.lean: {exc}",
                    object_ref=node_path,
                    details={"path": str(path)},
                )
            )
        return self.foundation.ok(
            ProjectionView(
                node_path=node_path,
                projection_kind="interfaces",
                path=str(path),
                changed=changed,
                line_count=len(rendered.value.splitlines()),
                summary=("Updated generated Interfaces.lean." if changed else "Generated Interfaces.lean is already synchronized."),
            ),
            warnings=rendered.issues,
        )

    def check_interfaces_sync(self, repo_root: Path, *, node_path: str) -> ServiceResult[GateReport]:
        rendered = self.render_interfaces(repo_root, node_path=node_path)
        if not rendered.ok or rendered.value is None:
            return self.foundation.fail(rendered.issues)
        path = self._interfaces_path(repo_root, node_path)
        if not path.exists():
            return self.foundation.ok(
                self.foundation.gate_failed(
                    "interfaces_sync",
                    self.foundation.issue(
                        "interfaces_projection_missing",
                        "Generated Interfaces.lean is missing.",
                        object_ref=node_path,
                        details={"path": str(path)},
                    ),
                    summary="Generated Interfaces.lean is missing.",
                )
            )
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError as exc:
            return self.foundation.fail(
                self.foundation.issue(
                    "interfaces_projection_read_failed",
                    f"Failed to read generated Interfaces.lean: {exc}",
                    object_ref=node_path,
                    details={"path": str(path)},
                )
            )
        if actual != rendered.value:
            return self.foundation.ok(
                self.foundation.gate_failed(
                    "interfaces_sync",
                    self.foundation.issue(
                        "interfaces_projection_stale",
                        "Generated Interfaces.lean does not match current public exports.",
                        object_ref=node_path,
                        details={"path": str(path)},
                    ),
                    summary="Generated Interfaces.lean is stale.",
                )
            )
        return self.foundation.ok(
            self.foundation.gate_passed(
                "interfaces_sync",
                summary="Generated Interfaces.lean is synchronized.",
                warnings=rendered.issues,
            )
        )

    def _prelude_path(self, repo_root: Path, node_path: str) -> Path:
        return self.foundation.prelude_path(FoundationContext(repo_root=Path(repo_root)), node_path)

    def _interfaces_path(self, repo_root: Path, node_path: str) -> Path:
        return self.foundation.interfaces_path(FoundationContext(repo_root=Path(repo_root)), node_path)

    def _content_interface_imports(self, repo_root: Path, *, node_path: str) -> ServiceResult[list[str]]:
        public = self.export.list_content_public_decls(repo_root, node_path=node_path)
        if not public.ok or public.value is None:
            return self.foundation.fail(public.issues)
        imports: set[str] = set()
        for decl in public.value:
            if not decl.public:
                continue
            if decl.ref.repo is not None:
                return self.foundation.fail(
                    self.foundation.issue(
                        "interfaces_decl_cross_repo_unsupported",
                        "Native Content Interfaces.lean cannot project cross-repo DeclRef entries.",
                        object_ref=node_path,
                        current=decl.ref.repo,
                    )
                )
            if not decl.ready or decl.stale:
                return self.foundation.fail(
                    self.foundation.issue(
                        "interfaces_decl_not_ready",
                        f"Public declaration is not ready for Interfaces.lean projection: {decl.ref.name}",
                        object_ref=node_path,
                        current=f"ready={decl.ready}, stale={decl.stale}",
                        expected="ready=True, stale=False",
                    )
                )
            imports.add(self._decl_owned_module(decl.ref, decl.kind))
        return self.foundation.ok(sorted(imports), warnings=public.issues)

    def _scope_interface_imports(self, repo_root: Path, *, scope_path: str) -> ServiceResult[list[str]]:
        gate = self.export.validate_scope_exports(repo_root, scope_path=scope_path)
        if not gate.ok or gate.value is None:
            return self.foundation.fail(gate.issues)
        if not gate.value.passed:
            return self.foundation.fail(gate.value.issues)
        contract = self.contract.get_current_contract(repo_root, node_path=scope_path)
        if not contract.ok or contract.value is None:
            return self.foundation.fail(contract.issues)
        candidates = self.export.list_scope_export_candidates(repo_root, scope_path=scope_path)
        if not candidates.ok or candidates.value is None:
            return self.foundation.fail(candidates.issues)
        by_key = {self._decl_ref_key(candidate.ref): candidate for candidate in candidates.value.candidates}
        imports: set[str] = set()
        for ref in contract.value.contract.exports:
            candidate = by_key.get(self._decl_ref_key(ref))
            if candidate is None:
                return self.foundation.fail(
                    self.foundation.issue(
                        "interfaces_export_candidate_missing",
                        f"Scope export has no visible projection candidate: {ref.name}",
                        object_ref=scope_path,
                    )
                )
            if candidate.source_kind == NodeKind.SCOPE.value:
                imports.add(f"{candidate.source_child}.Interfaces")
            else:
                imports.add(self._decl_owned_module(ref, candidate.kind))
        return self.foundation.ok(sorted(imports), warnings=candidates.issues)

    def _prelude_imports(self, node_path: str, deps: list[dict[str, Any]], mathlib_modules: list[dict[str, Any]]) -> list[str]:
        imports: set[str] = set()
        for dep in deps:
            provider = self._provider_interfaces_module(node_path, dep)
            if provider:
                imports.add(provider)
        for item in mathlib_modules:
            module = self._mathlib_module_name(item)
            if module:
                imports.add(module)
        return sorted(imports)

    def _provider_interfaces_module(self, node_path: str, dep: dict[str, Any]) -> str | None:
        if not isinstance(dep, dict):
            return None
        target = dep.get("target") or dep.get("node") or dep.get("provider")
        repo: str | None = None
        provider_node: str | None = None
        if isinstance(target, dict):
            repo_value = target.get("repo")
            node_value = target.get("node") or target.get("path")
            repo = str(repo_value).strip() if repo_value is not None and str(repo_value).strip() else None
            provider_node = str(node_value).strip() if node_value is not None and str(node_value).strip() else None
        elif isinstance(target, str):
            provider_node = target.strip()
        if provider_node is None:
            provider_node = self._optional_text(dep.get("node_path") or dep.get("provider_node") or dep.get("provider_node_path"))
        if provider_node is None:
            return None
        if repo is None and provider_node == node_path:
            return None
        boundary = provider_node or "Main"
        return f"{repo}.{boundary}.Interfaces" if repo else f"{boundary}.Interfaces"

    def _mathlib_module_name(self, item: dict[str, Any] | str) -> str | None:
        if isinstance(item, str):
            return item.strip() or None
        if not isinstance(item, dict):
            return None
        candidates = [
            item.get("module"),
            item.get("name"),
            item.get("module_name"),
        ]
        ref = item.get("ref")
        if isinstance(ref, dict):
            candidates.extend([ref.get("module"), ref.get("name")])
        for candidate in candidates:
            text = self._optional_text(candidate)
            if text:
                return text
        return None

    def _optional_text(self, value: Any) -> str | None:
        if value is None:
            return None
        text = str(value).strip()
        return text or None

    def _decl_owned_module(self, ref: DeclRef, kind: str | None) -> str:
        return f"{ref.node}.{self._decl_kind_dir(kind)}.{ref.name}"

    def _decl_kind_dir(self, kind: str | None) -> str:
        normalized = (kind or "other").strip().lower().replace("-", "_")
        if normalized in {"definition", "def", "defs"}:
            return "Defs"
        if normalized in {"structure", "class", "type", "types"}:
            return "Types"
        if normalized in {"instance", "instances"}:
            return "Instances"
        if normalized in {"lemma", "lemmas"}:
            return "Lemmas"
        if normalized in {"theorem", "theorems", "proposition", "corollary"}:
            return "Theorems"
        return "Defs"

    def _decl_ref_key(self, ref: DeclRef) -> tuple[str | None, str, str, int]:
        return (ref.repo, ref.node, ref.name, ref.revision)

    def _is_safe_import_module(self, value: str) -> bool:
        if not value or any(ch.isspace() for ch in value):
            return False
        if "/" in value or "\\" in value or ".." in value:
            return False
        return all(bool(part) for part in value.split("."))
